/*
 * This class was automatically generated by jros2
 */
package statistics_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
*/
public class StatisticDataType implements ROS2Message<StatisticDataType>
{
   public static final java.lang.String name = "statistics_msgs::msg::dds_::StatisticDataType_";

   public StatisticDataType()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(StatisticDataType from)
   {
   }

}