/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(rosgraph_msgs/Clock)
##################################################################################
##################################################################################

 */
package rosgraph_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class Clock implements ROS2Message<Clock>
{
   public static final java.lang.String name = "rosgraph_msgs::msg::dds_::Clock_";

   /**
      # This message communicates the current time.
      #
      # For more information, see https://design.ros2.org/articles/clock_and_time.html.
   */
   private final rosgraph_msgs.msg.dds.builtin_interfaces/Time clock_;

   public Clock()
   {
      clock_ = new rosgraph_msgs.msg.dds.builtin_interfaces/Time();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += clock_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      clock_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      clock_.deserialize(buffer);

   }

   @Override
   public void set(Clock from)
   {
      clock_.set(from.clock_);

   }

   public rosgraph_msgs.msg.dds.builtin_interfaces/Time getClock()
   {
      return clock_;
   }


}