/*
 * This class was automatically generated by jros2
 */
package lifecycle_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
*/
public class State implements ROS2Message<State>
{
   public static final java.lang.String name = "lifecycle_msgs::msg::dds_::State_";

   /**
      The state id value from the above definitions.
   */
   private byte id_;
   /**
      A text label of the state.
   */
   private StringBuilder label_;

   public State()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // id_
      currentAlignment += -1 + CDRBuffer.alignment(currentAlignment, -1); // label_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(id_);
      buffer.writeString(label_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      id_ = buffer.readByte();
      buffer.readString(label_);

   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(State from)
   {
      id_ = from.id_;
      label_ = from.label_;

   }

   public byte getid()
   {
      return id_;
   }

   public void setid(byte id_)
   {
      this.id_ = id_;
   }

   public StringBuilder getlabel()
   {
      return label_;
   }

   public void setlabel(StringBuilder label_)
   {
      this.label_ = label_;
   }


}