#!/usr/bin/env python3
"""
Convert JAXB-annotated Java classes to Jackson XML annotations.
"""

import os
import re
import sys

def convert_file(filepath):
    with open(filepath, 'r') as f:
        content = f.read()

    original_content = content

    # Add header comment if not already present
    if not content.startswith('//'):
        header = '''//
// This file is auto-generated. Do not modify directly.
// Generated by jros2 build process from Fast-DDS XSD schema.
//
'''
        content = header + content

    # Remove all JAXB imports (both javax and jakarta)
    content = re.sub(r'import javax\.xml\.bind\..*?;\n', '', content)
    content = re.sub(r'import jakarta\.xml\.bind\..*?;\n', '', content)

    # Add Jackson imports after package declaration with line break (only if not already present)
    if 'import com.fasterxml.jackson.annotation.*' not in content:
        package_match = re.search(r'(package .*?;)', content)
        if package_match:
            package_line = package_match.group(1)
            jackson_imports = '''

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
'''
            content = content.replace(package_line, package_line + jackson_imports, 1)

    # Remove duplicate imports (keep only first occurrence)
    import_lines = []
    import_pattern = re.compile(r'^import .*?;$', re.MULTILINE)
    seen_imports = set()

    def deduplicate_import(match):
        import_line = match.group(0)
        if import_line in seen_imports:
            return ''  # Remove duplicate
        seen_imports.add(import_line)
        return import_line

    content = import_pattern.sub(deduplicate_import, content)

    # Clean up excessive blank lines (reduce multiple blank lines to maximum 2)
    content = re.sub(r'\n{4,}', '\n\n\n', content)

    # Remove XmlElements blocks first (before converting individual XmlElement)
    content = re.sub(r'@XmlElements\s*\(\s*\{[^}]*\}\s*\)', '', content, flags=re.DOTALL)

    # Convert annotations in specific order (most specific first)

    # XmlAttribute with parameters
    content = re.sub(r'@XmlAttribute\s*\(\s*name\s*=\s*"([^"]*)"\s*,\s*required\s*=\s*(true|false)\s*\)',
                    r'@JacksonXmlProperty(isAttribute = true, localName = "\1")', content)
    content = re.sub(r'@XmlAttribute\s*\(\s*name\s*=\s*"([^"]*)"\s*\)',
                    r'@JacksonXmlProperty(isAttribute = true, localName = "\1")', content)
    content = re.sub(r'@XmlAttribute(?!\s*\()', r'@JacksonXmlProperty(isAttribute = true)', content)

    # XmlElement with parameters (handle all parameter combinations)
    # XmlElement with name and required
    content = re.sub(r'@XmlElement\s*\(\s*name\s*=\s*"([^"]*)"\s*,\s*required\s*=\s*(true|false)\s*\)',
                    r'@JacksonXmlProperty(localName = "\1")', content)
    # XmlElement with type parameter (remove it - Jackson will infer type)
    content = re.sub(r'@XmlElement\s*\(\s*type\s*=\s*[^)]*\s*\)', '', content)
    # XmlElement with just required (remove it)
    content = re.sub(r'@XmlElement\s*\(\s*required\s*=\s*(true|false)\s*\)', '', content)
    # XmlElement with defaultValue (remove it)
    content = re.sub(r'@XmlElement\s*\(\s*defaultValue\s*=\s*"[^"]*"\s*\)', '', content)
    # XmlElement with just name
    content = re.sub(r'@XmlElement\s*\(\s*name\s*=\s*"([^"]*)"\s*\)',
                    r'@JacksonXmlProperty(localName = "\1")', content)
    # XmlElement without parameters
    content = re.sub(r'@XmlElement(?!\s*\()', r'@JacksonXmlProperty', content)

    # Other simple annotations
    content = re.sub(r'@XmlEnumValue\s*\(\s*"([^"]*)"\s*\)', r'@JsonProperty("\1")', content)
    content = re.sub(r'@XmlValue', '@JacksonXmlText', content)
    content = re.sub(r'@XmlRootElement\s*\(\s*name\s*=\s*"([^"]*)"\s*\)', r'@JacksonXmlRootElement(localName = "\1")', content)
    content = re.sub(r'@XmlRootElement(?!\s*\()', r'@JacksonXmlRootElement', content)

    # XmlType - just remove it or replace with root element
    content = re.sub(r'@XmlType\s*\([^)]*\)', '', content)

    # XmlAccessorType
    content = re.sub(r'@XmlAccessorType\s*\(\s*XmlAccessType\.FIELD\s*\)',
                    '@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY, getterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)',
                    content)

    # Remove annotations without Jackson equivalents
    content = re.sub(r'@XmlSchemaType[^\n]*\n', '', content)
    content = re.sub(r'@XmlRegistry[^\n]*\n', '', content)
    content = re.sub(r'@XmlEnum[^\n]*\n', '', content)
    content = re.sub(r'@XmlSeeAlso\s*\([^)]*\)[^\n]*\n', '', content, flags=re.DOTALL)

    # Remove XmlElementDecl (multi-line aware)
    content = re.sub(r'@XmlElementDecl\s*\([^)]*\)', '', content, flags=re.DOTALL)

    # Remove XmlElementRef, XmlElementRefs, XmlElements (choice/polymorphism annotations)
    # Also remove their Jackson equivalents that don't exist
    # These are multi-line, so we need to be more aggressive
    content = re.sub(r'@XmlElementRef[^@]*?(?=@|\n\s*protected|\n\s*public|\n\s*private|\Z)', '', content, flags=re.DOTALL)
    content = re.sub(r'@XmlElementRefs[^@]*?(?=@|\n\s*protected|\n\s*public|\n\s*private|\Z)', '', content, flags=re.DOTALL)
    content = re.sub(r'@XmlElements[^@]*?(?=@|\n\s*protected|\n\s*public|\n\s*private|\Z)', '', content, flags=re.DOTALL)
    content = re.sub(r'@JacksonXmlPropertyRef[^@]*?(?=@|\n\s*protected|\n\s*public|\n\s*private|\Z)', '', content, flags=re.DOTALL)
    content = re.sub(r'@JacksonXmlPropertyRefs[^@]*?(?=@|\n\s*protected|\n\s*public|\n\s*private|\Z)', '', content, flags=re.DOTALL)
    content = re.sub(r'@JacksonXmlPropertys[^@]*?(?=@|\n\s*protected|\n\s*public|\n\s*private|\Z)', '', content, flags=re.DOTALL)

    # Remove JAXBElement references
    # For List<JAXBElement<String>> -> List<String>
    content = re.sub(r'List<JAXBElement<String>>', 'List<String>', content)
    # For List<JAXBElement<?>> -> List<Object>
    content = re.sub(r'List<JAXBElement<\?>>', 'List<Object>', content)
    # For JAXBElement<?> -> Object
    content = re.sub(r'JAXBElement<\?>', 'Object', content)
    # For JAXBElement<SomeType> -> SomeType
    content = re.sub(r'JAXBElement<([^>]+)>', r'\1', content)

    # Remove JAXBElement import
    content = re.sub(r'import jakarta\.xml\.bind\.JAXBElement;\n', '', content)

    if content != original_content:
        with open(filepath, 'w') as f:
            f.write(content)
        print(f"Converted: {filepath}")
    else:
        print(f"No changes: {filepath}")

def main():
    if len(sys.argv) < 2:
        print("Usage: convert_jaxb_to_jackson.py <directory>")
        sys.exit(1)

    gen_dir = sys.argv[1]

    for root, dirs, files in os.walk(gen_dir):
        for file in files:
            if file.endswith('.java'):
                filepath = os.path.join(root, file)
                convert_file(filepath)

if __name__ == '__main__':
    main()
