/*
 * This class was automatically generated by jros2
 */
package visualization_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
*/
public class ImageMarker implements ROS2Message<ImageMarker>
{
   public static final java.lang.String name = "visualization_msgs::msg::dds_::ImageMarker_";

   /**
      Namespace which is used with the id to form a unique id.
   */
   private StringBuilder ns_;
   /**
      Unique id within the namespace.
   */
   private int id_;
   /**
      One of the above types, e.g. CIRCLE, LINE_STRIP, etc.
   */
   private int type_;
   /**
      Either ADD or REMOVE.
   */
   private int action_;
   /**
      The scale of the object, e.g. the diameter for a CIRCLE.
   */
   private float scale_;
   /**
      Whether or not to fill in the shape with color.
   */
   private byte filled_;

   public ImageMarker()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += -1 + CDRBuffer.alignment(currentAlignment, -1); // ns_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // type_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // action_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // scale_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // filled_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(ns_);
      buffer.writeInt(id_);
      buffer.writeInt(type_);
      buffer.writeInt(action_);
      buffer.writeFloat(scale_);
      buffer.writeByte(filled_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(ns_);
      id_ = buffer.readInt();
      type_ = buffer.readInt();
      action_ = buffer.readInt();
      scale_ = buffer.readFloat();
      filled_ = buffer.readByte();

   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(ImageMarker from)
   {
      ns_ = from.ns_;
      id_ = from.id_;
      type_ = from.type_;
      action_ = from.action_;
      scale_ = from.scale_;
      filled_ = from.filled_;

   }

   public StringBuilder getns()
   {
      return ns_;
   }

   public void setns(StringBuilder ns_)
   {
      this.ns_ = ns_;
   }

   public int getid()
   {
      return id_;
   }

   public void setid(int id_)
   {
      this.id_ = id_;
   }

   public int gettype()
   {
      return type_;
   }

   public void settype(int type_)
   {
      this.type_ = type_;
   }

   public int getaction()
   {
      return action_;
   }

   public void setaction(int action_)
   {
      this.action_ = action_;
   }

   public float getscale()
   {
      return scale_;
   }

   public void setscale(float scale_)
   {
      this.scale_ = scale_;
   }

   public byte getfilled()
   {
      return filled_;
   }

   public void setfilled(byte filled_)
   {
      this.filled_ = filled_;
   }


}