/*
 * This class was automatically generated by jros2
 */
package visualization_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
*/
public class InteractiveMarkerPose implements ROS2Message<InteractiveMarkerPose>
{
   public static final String name = "visualization_msgs::msg::dds_::InteractiveMarkerPose_";

   /**
       Identifying string. Must be globally unique in
       the topic that this message is sent through.
   */
   private StringBuilder name_;

   public InteractiveMarkerPose()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += -1 + CDRBuffer.alignment(currentAlignment, -1); // name_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.(name_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      name_ = buffer.();

   }

   @Override
   public String getName()
   {
      return name;
   }

   @Override
   public void set(InteractiveMarkerPose from)
   {
      name_ = from.name_;

   }

   public StringBuilder getname()
   {
      return name_;
   }

   public void setname(StringBuilder name_)
   {
      this.name_ = name_;
   }


}