/*
 * This class was automatically generated by jros2
 */
package visualization_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class MarkerArray implements ROS2Message<MarkerArray>
{
   public static final String name = "visualization_msgs::msg::dds_::MarkerArray_";

   private visualization_msgs.msg.dds.Marker markers_;

   public MarkerArray()
   {
      markers_ = new visualization_msgs.msg.dds.Marker();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public String getName()
   {
      return name;
   }

   @Override
   public void set(MarkerArray from)
   {
   }

   public visualization_msgs.msg.dds.Marker getmarkers()
   {
      return markers_;
   }


}