/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package nav_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (nav_msgs/GetPlan_Response):
<pre>{@code
# Array of poses from start to goal if one was successfully found.
Path plan}</pre>
*/
public class GetPlan_Response implements ROS2Message<GetPlan_Response>
{
   public static final java.lang.String name = "nav_msgs::srv::dds_::GetPlanResponse_";

   /**
      Array of poses from start to goal if one was successfully found.
   */
   private final nav_msgs.Path plan_;

   public GetPlan_Response()
   {
      plan_ = new nav_msgs.Path();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += plan_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      plan_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      plan_.deserialize(buffer);

   }

   @Override
   public void set(GetPlan_Response from)
   {
      plan_.set(from.plan_);

   }

   public nav_msgs.Path getPlan()
   {
      return plan_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("GetPlan_Response {");
      builder.append("plan_=");
      builder.append(plan_);

      builder.append("}");
      return builder.toString();
   }
}
