/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package nav_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (nav_msgs/LoadMap_Request):
<pre>{@code
# URL of map resource
# Can be an absolute path to a file: file:///path/to/maps/floor1.yaml
# Or, relative to a ROS package: package://my_ros_package/maps/floor2.yaml
string map_url}</pre>
*/
public class LoadMap_Request implements ROS2Message<LoadMap_Request>
{
   public static final java.lang.String name = "nav_msgs::msg::dds_::LoadMapRequest_";

   /**
      URL of map resource
      Can be an absolute path to a file: file:///path/to/maps/floor1.yaml
      Or, relative to a ROS package: package://my_ros_package/maps/floor2.yaml
   */
   private final StringBuilder map_url_;

   public LoadMap_Request()
   {
      map_url_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (2 * map_url_.length()) + 1; // map_url_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(map_url_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(map_url_);

   }

   @Override
   public void set(LoadMap_Request from)
   {
      map_url_.delete(0, map_url_.length());
      map_url_.insert(0, from.map_url_);

   }

   public StringBuilder getMapUrl()
   {
      return map_url_;
   }

   public java.lang.String getMapUrlAsString()
   {
      return map_url_.toString();
   }

   public void setMapUrl(java.lang.String s)
   {
      this.map_url_.delete(0, this.map_url_.length());
      this.map_url_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("LoadMap_Request {");
      builder.append("map_url_=");
      builder.append(map_url_.toString());

      builder.append("}");
      return builder.toString();
   }
}
