/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package nav_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (nav_msgs/LoadMap_Response):
<pre>{@code
# Result code defintions
uint8 RESULT_SUCCESS=0
uint8 RESULT_MAP_DOES_NOT_EXIST=1
uint8 RESULT_INVALID_MAP_DATA=2
uint8 RESULT_INVALID_MAP_METADATA=3
uint8 RESULT_UNDEFINED_FAILURE=255

# Returned map is only valid if result equals RESULT_SUCCESS
nav_msgs/OccupancyGrid map
uint8 result}</pre>
*/
public class LoadMap_Response implements ROS2Message<LoadMap_Response>
{
   public static final java.lang.String name = "nav_msgs::srv::dds_::LoadMapResponse_";

   /**
      Result code defintions
   */
   public static final short RESULT_SUCCESS = 0;
   public static final short RESULT_MAP_DOES_NOT_EXIST = 1;
   public static final short RESULT_INVALID_MAP_DATA = 2;
   public static final short RESULT_INVALID_MAP_METADATA = 3;
   public static final short RESULT_UNDEFINED_FAILURE = 255;
   /**
      Returned map is only valid if result equals RESULT_SUCCESS
   */
   private final nav_msgs.OccupancyGrid map_;
   private short result_;

   public LoadMap_Response()
   {
      map_ = new nav_msgs.OccupancyGrid();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += map_.calculateSizeBytes(currentAlignment);
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // result_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      map_.serialize(buffer);
      buffer.writeShort(result_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      map_.deserialize(buffer);
      result_ = buffer.readShort();

   }

   @Override
   public void set(LoadMap_Response from)
   {
      map_.set(from.map_);
      result_ = from.result_;

   }

   public nav_msgs.OccupancyGrid getMap()
   {
      return map_;
   }

   public short getResult()
   {
      return result_;
   }

   public void setResult(short result_)
   {
      this.result_ = result_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("LoadMap_Response {");
      builder.append("RESULT_SUCCESS=");
      builder.append(RESULT_SUCCESS);
      builder.append("RESULT_MAP_DOES_NOT_EXIST=");
      builder.append(RESULT_MAP_DOES_NOT_EXIST);
      builder.append("RESULT_INVALID_MAP_DATA=");
      builder.append(RESULT_INVALID_MAP_DATA);
      builder.append("RESULT_INVALID_MAP_METADATA=");
      builder.append(RESULT_INVALID_MAP_METADATA);
      builder.append("RESULT_UNDEFINED_FAILURE=");
      builder.append(RESULT_UNDEFINED_FAILURE);
      builder.append("map_=");
      builder.append(map_);
      builder.append("result_=");
      builder.append(result_);

      builder.append("}");
      return builder.toString();
   }
}
