/*
 * This class was automatically generated by jros2
 */
package sensor_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   Measurement from an external time source not actively synchronized with the system clock.
*/
public class TimeReference implements ROS2Message<TimeReference>
{
   public static final java.lang.String name = "sensor_msgs::msg::dds_::TimeReference_";

   private final std_msgs.msg.dds.Header header_;
   private final builtin_interfaces.msg.dds.Time time_ref_;
   private final StringBuilder source_;

   public TimeReference()
   {
      header_ = new std_msgs.msg.dds.Header();
      time_ref_ = new builtin_interfaces.msg.dds.Time();
      source_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += -1 + CDRBuffer.alignment(currentAlignment, -1); // source_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(source_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(source_);

   }

   @Override
   public void set(TimeReference from)
   {
      source_.delete(0, source_.length());
      source_.insert(0, from.source_);

   }

   public std_msgs.msg.dds.Header getheader()
   {
      return header_;
   }

   public builtin_interfaces.msg.dds.Time gettime_ref()
   {
      return time_ref_;
   }

   public StringBuilder getsource()
   {
      return source_;
   }


}