/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(jros2_example_interfaces/StringTest.msg)
##################################################################################
   # https://design.ros2.org/articles/interface_definition.html

   string my_string1 "I heard \"Hello\""   # valid
   string my_string2 "I heard "Hello""     # not valid
   string my_string3 "I heard 'Hello'"     # valid
   string my_string4 'I heard \'Hello\''   # valid
   string my_string5 'I heard 'Hello''     # not valid
   string my_string6 'I heard "Hello"'     # valid

##################################################################################

 */
package jros2_example_interfaces.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   https://design.ros2.org/articles/interface_definition.html
*/
public class StringTest implements ROS2Message<StringTest>
{
   public static final java.lang.String name = "jros2_example_interfaces::msg::dds_::StringTest_";

   private final StringBuilder my_string1_; // valid
   private final StringBuilder my_string2_; // not valid
   private final StringBuilder my_string3_; // valid
   private final StringBuilder my_string4_; // valid
   private final StringBuilder my_string5_; // not valid
   private final StringBuilder my_string6_; // valid

   public StringTest()
   {
      my_string1_ = new StringBuilder("I heard \"Hello\"");
      my_string2_ = new StringBuilder("I heard \"Hello\"");
      my_string3_ = new StringBuilder("I heard 'Hello'");
      my_string4_ = new StringBuilder("I heard \'Hello\'");
      my_string5_ = new StringBuilder("I heard 'Hello'");
      my_string6_ = new StringBuilder("I heard \"Hello\"");

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * my_string1_.length()) + 1; // my_string1_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * my_string2_.length()) + 1; // my_string2_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * my_string3_.length()) + 1; // my_string3_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * my_string4_.length()) + 1; // my_string4_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * my_string5_.length()) + 1; // my_string5_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * my_string6_.length()) + 1; // my_string6_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(my_string1_);
      buffer.writeString(my_string2_);
      buffer.writeString(my_string3_);
      buffer.writeString(my_string4_);
      buffer.writeString(my_string5_);
      buffer.writeString(my_string6_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(my_string1_);
      buffer.readString(my_string2_);
      buffer.readString(my_string3_);
      buffer.readString(my_string4_);
      buffer.readString(my_string5_);
      buffer.readString(my_string6_);

   }

   @Override
   public void set(StringTest from)
   {
      my_string1_.delete(0, my_string1_.length());
      my_string1_.insert(0, from.my_string1_);
      my_string2_.delete(0, my_string2_.length());
      my_string2_.insert(0, from.my_string2_);
      my_string3_.delete(0, my_string3_.length());
      my_string3_.insert(0, from.my_string3_);
      my_string4_.delete(0, my_string4_.length());
      my_string4_.insert(0, from.my_string4_);
      my_string5_.delete(0, my_string5_.length());
      my_string5_.insert(0, from.my_string5_);
      my_string6_.delete(0, my_string6_.length());
      my_string6_.insert(0, from.my_string6_);

   }

   public StringBuilder getMyString1()
   {
      return my_string1_;
   }

   public StringBuilder getMyString2()
   {
      return my_string2_;
   }

   public StringBuilder getMyString3()
   {
      return my_string3_;
   }

   public StringBuilder getMyString4()
   {
      return my_string4_;
   }

   public StringBuilder getMyString5()
   {
      return my_string5_;
   }

   public StringBuilder getMyString6()
   {
      return my_string6_;
   }


}