/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
(std_msgs/Byte.msg):
##################################################################################
        # This was originally provided as an example message.
        # It is deprecated as of Foxy
        # It is recommended to create your own semantically meaningful message.
        # However if you would like to continue using this please use the equivalent in example_msgs.

        byte data

##################################################################################

 */
package std_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   This was originally provided as an example message.
   It is deprecated as of Foxy
   It is recommended to create your own semantically meaningful message.
   However if you would like to continue using this please use the equivalent in example_msgs.
*/
public class Byte implements ROS2Message<Byte>
{
   public static final java.lang.String name = "std_msgs::msg::dds_::Byte_";

   private byte data_;

   public Byte()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // data_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(data_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      data_ = buffer.readByte();

   }

   @Override
   public void set(Byte from)
   {
      data_ = from.data_;

   }

   public byte getdata()
   {
      return data_;
   }

   public void setdata(byte data_)
   {
      this.data_ = data_;
   }


}