/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
(std_msgs/Char.msg):
##################################################################################
   # This was originally provided as an example message.
   # It is deprecated as of Foxy
   # It is recommended to create your own semantically meaningful message.
   # However if you would like to continue using this please use the equivalent in example_msgs.

   char data

##################################################################################

 */
package std_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   This was originally provided as an example message.
   It is deprecated as of Foxy
   It is recommended to create your own semantically meaningful message.
   However if you would like to continue using this please use the equivalent in example_msgs.
*/
public class Char implements ROS2Message<Char>
{
   public static final java.lang.String name = "std_msgs::msg::dds_::Char_";

   private char data_;

   public Char()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // data_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeChar(data_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      data_ = buffer.readChar();

   }

   @Override
   public void set(Char from)
   {
      data_ = from.data_;

   }

   public char getdata()
   {
      return data_;
   }

   public void setdata(char data_)
   {
      this.data_ = data_;
   }


}