/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(std_msgs/Float32MultiArray.msg)
##################################################################################
   # This was originally provided as an example message.
   # It is deprecated as of Foxy
   # It is recommended to create your own semantically meaningful message.
   # However if you would like to continue using this please use the equivalent in example_msgs.

   # Please look at the MultiArrayLayout message definition for
   # documentation on all multiarrays.

   MultiArrayLayout  layout        # specification of data layout
   float32[]         data          # array of data

##################################################################################

 */
package std_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   Please look at the MultiArrayLayout message definition for
   documentation on all multiarrays.
*/
public class Float32MultiArray implements ROS2Message<Float32MultiArray>
{
   public static final java.lang.String name = "std_msgs::msg::dds_::Float32MultiArray_";

   public Float32MultiArray()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public void set(Float32MultiArray from)
   {
   }

}