/*
 * This class was automatically generated by jros2
 */
package std_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   Please look at the MultiArrayLayout message definition for
   documentation on all multiarrays.
*/
public class Int8MultiArray implements ROS2Message<Int8MultiArray>
{
   public static final java.lang.String name = "std_msgs::msg::dds_::Int8MultiArray_";

   public Int8MultiArray()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public void set(Int8MultiArray from)
   {
   }

}