/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 *
 * Original .msg file content (std_msgs/UInt64.msg):

# This was originally provided as an example message.
# It is deprecated as of Foxy
# It is recommended to create your own semantically meaningful message.
# However if you would like to continue using this please use the equivalent in example_msgs.

uint64 data


 */
package std_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   This was originally provided as an example message.
   It is deprecated as of Foxy
   It is recommended to create your own semantically meaningful message.
   However if you would like to continue using this please use the equivalent in example_msgs.
*/
public class UInt64 implements ROS2Message<UInt64>
{
   public static final java.lang.String name = "std_msgs::msg::dds_::UInt64_";

   private long data_;

   public UInt64()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // data_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(data_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      data_ = buffer.readLong();

   }

   @Override
   public void set(UInt64 from)
   {
      data_ = from.data_;

   }

   public long getdata()
   {
      return data_;
   }

   public void setdata(long data_)
   {
      this.data_ = data_;
   }


}