/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package std_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This was originally provided as an example message.
It is deprecated as of Foxy
It is recommended to create your own semantically meaningful message.
However if you would like to continue using this please use the equivalent in example_msgs.
<p>Source (std_msgs/UInt16):
<pre>{@code
# This was originally provided as an example message.
# It is deprecated as of Foxy
# It is recommended to create your own semantically meaningful message.
# However if you would like to continue using this please use the equivalent in example_msgs.

uint16 data
}</pre>
*/
public class UInt16 implements ROS2Message<UInt16>
{
   public static final java.lang.String name = "std_msgs::msg::dds_::UInt16_";

   private int data_;

   public UInt16()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // data_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeInt(data_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      data_ = buffer.readInt();

   }

   @Override
   public void set(UInt16 from)
   {
      data_ = from.data_;

   }

   public int getData()
   {
      return data_;
   }

   public void setData(int data_)
   {
      this.data_ = data_;
   }


}