/*
 * This class was automatically generated by jros2
 */
package sensor_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
*/
public class JointState implements ROS2Message<JointState>
{
   public static final String name = "sensor_msgs::msg::dds_::JointState_";

   private  name_;
   private IDLDoubleSequence position_;
   private IDLDoubleSequence velocity_;
   private IDLDoubleSequence effort_;

   public JointState()
   {
      name_ = new ();
      position_ = new IDLDoubleSequence();
      velocity_ = new IDLDoubleSequence();
      effort_ = new IDLDoubleSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += name_.calculateSizeBytes(currentAlignment);
      currentAlignment += position_.calculateSizeBytes(currentAlignment);
      currentAlignment += velocity_.calculateSizeBytes(currentAlignment);
      currentAlignment += effort_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      name_.serialize(buffer);
      position_.serialize(buffer);
      velocity_.serialize(buffer);
      effort_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      name_.deserialize(buffer);
      position_.deserialize(buffer);
      velocity_.deserialize(buffer);
      effort_.deserialize(buffer);

   }

   @Override
   public String getName()
   {
      return name;
   }

   @Override
   public void set(JointState from)
   {
      name_.set(from.name_);
      position_.set(from.position_);
      velocity_.set(from.velocity_);
      effort_.set(from.effort_);

   }

   public  getname()
   {
      return name_;
   }

   public IDLDoubleSequence getposition()
   {
      return position_;
   }

   public IDLDoubleSequence getvelocity()
   {
      return velocity_;
   }

   public IDLDoubleSequence geteffort()
   {
      return effort_;
   }


}