/*
 * This class was automatically generated by jros2
 */
package sensor_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
*/
public class NavSatStatus implements ROS2Message<NavSatStatus>
{
   public static final String name = "sensor_msgs::msg::dds_::NavSatStatus_";

   private byte status_;
   private short service_;

   public NavSatStatus()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // status_
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // service_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(status_);
      buffer.writeShort(service_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      status_ = buffer.readByte();
      service_ = buffer.readShort();

   }

   @Override
   public String getName()
   {
      return name;
   }

   @Override
   public void set(NavSatStatus from)
   {
      status_ = from.status_;
      service_ = from.service_;

   }

   public byte getstatus()
   {
      return status_;
   }

   public void setstatus(byte status_)
   {
      this.status_ = status_;
   }

   public short getservice()
   {
      return service_;
   }

   public void setservice(short service_)
   {
      this.service_ = service_;
   }


}