/*
 * This class was automatically generated by jros2
 */
package sensor_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
    frame_id is the location of the temperature reading
*/
public class Temperature implements ROS2Message<Temperature>
{
   public static final java.lang.String name = "sensor_msgs::msg::dds_::Temperature_";

   private double temperature_;
   private double variance_;

   public Temperature()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // temperature_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // variance_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(temperature_);
      buffer.writeDouble(variance_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      temperature_ = buffer.readDouble();
      variance_ = buffer.readDouble();

   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(Temperature from)
   {
      temperature_ = from.temperature_;
      variance_ = from.variance_;

   }

   public double gettemperature()
   {
      return temperature_;
   }

   public void settemperature(double temperature_)
   {
      this.temperature_ = temperature_;
   }

   public double getvariance()
   {
      return variance_;
   }

   public void setvariance(double variance_)
   {
      this.variance_ = variance_;
   }


}