/*
 * This class was automatically generated by jros2
 */
package sensor_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   Measurement from an external time source not actively synchronized with the system clock.
*/
public class TimeReference implements ROS2Message<TimeReference>
{
   public static final java.lang.String name = "sensor_msgs::msg::dds_::TimeReference_";

   private sensor_msgs.msg.dds.std_msgs/Header header_;
   private sensor_msgs.msg.dds.builtin_interfaces/Time time_ref_;
   private StringBuilder source_;

   public TimeReference()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += -1 + CDRBuffer.alignment(currentAlignment, -1); // source_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(source_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(source_);

   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(TimeReference from)
   {
      source_ = from.source_;

   }

   public sensor_msgs.msg.dds.std_msgs/Header getheader()
   {
      return header_;
   }

   public sensor_msgs.msg.dds.builtin_interfaces/Time gettime_ref()
   {
      return time_ref_;
   }

   public StringBuilder getsource()
   {
      return source_;
   }

   public void setsource(StringBuilder source_)
   {
      this.source_ = source_;
   }


}