/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package tf2_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (tf2_msgs/TF2Error):
<pre>{@code
uint8 NO_ERROR = 0
uint8 LOOKUP_ERROR = 1
uint8 CONNECTIVITY_ERROR = 2
uint8 EXTRAPOLATION_ERROR = 3
uint8 INVALID_ARGUMENT_ERROR = 4
uint8 TIMEOUT_ERROR = 5
uint8 TRANSFORM_ERROR = 6

uint8 error
string error_string
}</pre>
*/
public class TF2Error implements ROS2Message<TF2Error>
{
   public static final java.lang.String name = "tf2_msgs::msg::dds_::TF2Error_";

   public static final byte NO_ERROR = 0;
   public static final byte LOOKUP_ERROR = 1;
   public static final byte CONNECTIVITY_ERROR = 2;
   public static final byte EXTRAPOLATION_ERROR = 3;
   public static final byte INVALID_ARGUMENT_ERROR = 4;
   public static final byte TIMEOUT_ERROR = 5;
   public static final byte TRANSFORM_ERROR = 6;
   private byte error_;
   private final StringBuilder error_string_;

   public TF2Error()
   {
      error_string_ = new StringBuilder();

   }

   public TF2Error(TF2Error from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // error_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * error_string_.length()) + 1; // error_string_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(error_);
      buffer.writeString(error_string_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      error_ = buffer.readByte();
      buffer.readString(error_string_);

   }

   @Override
   public void set(TF2Error from)
   {
      error_ = from.error_;
      error_string_.delete(0, error_string_.length());
      error_string_.insert(0, from.error_string_);

   }

   public byte getError()
   {
      return error_;
   }

   public void setError(byte error_)
   {
      this.error_ = error_;
   }

   public StringBuilder getErrorString()
   {
      return error_string_;
   }

   public java.lang.String getErrorStringAsString()
   {
      return error_string_.toString();
   }

   public void setErrorString(java.lang.String s)
   {
      this.error_string_.delete(0, this.error_string_.length());
      this.error_string_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("TF2Error {");
      builder.append("NO_ERROR=");
      builder.append(NO_ERROR);
      builder.append("LOOKUP_ERROR=");
      builder.append(LOOKUP_ERROR);
      builder.append("CONNECTIVITY_ERROR=");
      builder.append(CONNECTIVITY_ERROR);
      builder.append("EXTRAPOLATION_ERROR=");
      builder.append(EXTRAPOLATION_ERROR);
      builder.append("INVALID_ARGUMENT_ERROR=");
      builder.append(INVALID_ARGUMENT_ERROR);
      builder.append("TIMEOUT_ERROR=");
      builder.append(TIMEOUT_ERROR);
      builder.append("TRANSFORM_ERROR=");
      builder.append(TRANSFORM_ERROR);
      builder.append("error_=");
      builder.append(error_);
      builder.append("error_string_=");
      builder.append(error_string_.toString());

      builder.append("}");
      return builder.toString();
   }
}