/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(visualization_msgs/InteractiveMarkerPose.msg)
##################################################################################

   # Time/frame info.
   std_msgs/Header header

   # Initial pose. Also, defines the pivot point for rotations.
   geometry_msgs/Pose pose

   # Identifying string. Must be globally unique in
   # the topic that this message is sent through.
   string name

##################################################################################

 */
package visualization_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
*/
public class InteractiveMarkerPose implements ROS2Message<InteractiveMarkerPose>
{
   public static final java.lang.String name = "visualization_msgs::msg::dds_::InteractiveMarkerPose_";

   /**
      Time/frame info.
   */
   private final std_msgs.msg.dds.Header header_;
   /**
      Initial pose. Also, defines the pivot point for rotations.
   */
   private final geometry_msgs.msg.dds.Pose pose_;
   /**
      Identifying string. Must be globally unique in
      the topic that this message is sent through.
   */
   private final StringBuilder name_;

   public InteractiveMarkerPose()
   {
      header_ = new std_msgs.msg.dds.Header();
      pose_ = new geometry_msgs.msg.dds.Pose();
      name_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += pose_.calculateSizeBytes(currentAlignment);
      currentAlignment += (1 * name_.length()) + CDRBuffer.alignment(currentAlignment, (1 * name_.length())); // name_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      pose_.serialize(buffer);
      buffer.writeString(name_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      pose_.deserialize(buffer);
      buffer.readString(name_);

   }

   @Override
   public void set(InteractiveMarkerPose from)
   {
      header_.set(from.header_);
      pose_.set(from.pose_);
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);

   }

   public std_msgs.msg.dds.Header getHeader()
   {
      return header_;
   }

   public geometry_msgs.msg.dds.Pose getPose()
   {
      return pose_;
   }

   public StringBuilder getName()
   {
      return name_;
   }


}