/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
(geometry_msgs/AccelStamped.msg):
##################################################################################
   # An accel with reference coordinate frame and timestamp
   std_msgs/Header header
   Accel accel

##################################################################################

 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class AccelStamped implements ROS2Message<AccelStamped>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::AccelStamped_";

   /**
      An accel with reference coordinate frame and timestamp
   */
   private final std_msgs.msg.dds.Header header_;
   private final geometry_msgs.msg.dds.Accel accel_;

   public AccelStamped()
   {
      header_ = new std_msgs.msg.dds.Header();
      accel_ = new geometry_msgs.msg.dds.Accel();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += accel_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      accel_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      accel_.deserialize(buffer);

   }

   @Override
   public void set(AccelStamped from)
   {
      header_.set(from.header_);
      accel_.set(from.accel_);

   }

   public std_msgs.msg.dds.Header getheader()
   {
      return header_;
   }

   public geometry_msgs.msg.dds.Accel getaccel()
   {
      return accel_;
   }


}