/*
 * This class was automatically generated by jros2
 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   A specification of a polygon where the first and last points are assumed to be connected
   It includes a unique identification field for disambiguating multiple instances
*/
public class PolygonInstance implements ROS2Message<PolygonInstance>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::PolygonInstance_";

   private final geometry_msgs.msg.dds.Polygon polygon_;
   private long id_;

   public PolygonInstance()
   {
      polygon_ = new geometry_msgs.msg.dds.Polygon();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += polygon_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // id_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      polygon_.serialize(buffer);
      buffer.writeLong(id_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      polygon_.deserialize(buffer);
      id_ = buffer.readLong();

   }

   @Override
   public void set(PolygonInstance from)
   {
      polygon_.set(from.polygon_);
      id_ = from.id_;

   }

   public geometry_msgs.msg.dds.Polygon getpolygon()
   {
      return polygon_;
   }

   public long getid()
   {
      return id_;
   }

   public void setid(long id_)
   {
      this.id_ = id_;
   }


}