/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(geometry_msgs/Quaternion.msg)
##################################################################################
   # This represents an orientation in free space in quaternion form.

   float64 x 0
   float64 y 0
   float64 z 0
   float64 w 1

##################################################################################

 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   This represents an orientation in free space in quaternion form.
*/
public class Quaternion implements ROS2Message<Quaternion>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::Quaternion_";

   private double x_;
   private double y_;
   private double z_;
   private double w_;

   public Quaternion()
   {
      x_ = 0;
      y_ = 0;
      z_ = 0;
      w_ = 1;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // x_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // y_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // z_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // w_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(x_);
      buffer.writeDouble(y_);
      buffer.writeDouble(z_);
      buffer.writeDouble(w_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      x_ = buffer.readDouble();
      y_ = buffer.readDouble();
      z_ = buffer.readDouble();
      w_ = buffer.readDouble();

   }

   @Override
   public void set(Quaternion from)
   {
      x_ = from.x_;
      y_ = from.y_;
      z_ = from.z_;
      w_ = from.w_;

   }

   public double getX()
   {
      return x_;
   }

   public void setX(double x_)
   {
      this.x_ = x_;
   }

   public double getY()
   {
      return y_;
   }

   public void setY(double y_)
   {
      this.y_ = y_;
   }

   public double getZ()
   {
      return z_;
   }

   public void setZ(double z_)
   {
      this.z_ = z_;
   }

   public double getW()
   {
      return w_;
   }

   public void setW(double w_)
   {
      this.w_ = w_;
   }


}