/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(geometry_msgs/Vector3Stamped.msg)
##################################################################################
   # This represents a Vector3 with reference coordinate frame and timestamp

   # Note that this follows vector semantics with it always anchored at the origin,
   # so the rotational elements of a transform are the only parts applied when transforming.

   std_msgs/Header header
   Vector3 vector

##################################################################################

 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   Note that this follows vector semantics with it always anchored at the origin,
   so the rotational elements of a transform are the only parts applied when transforming.
*/
public class Vector3Stamped implements ROS2Message<Vector3Stamped>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::Vector3Stamped_";

   private final std_msgs.msg.dds.Header header_;
   private final geometry_msgs.msg.dds.Vector3 vector_;

   public Vector3Stamped()
   {
      header_ = new std_msgs.msg.dds.Header();
      vector_ = new geometry_msgs.msg.dds.Vector3();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += vector_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      vector_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      vector_.deserialize(buffer);

   }

   @Override
   public void set(Vector3Stamped from)
   {
      header_.set(from.header_);
      vector_.set(from.vector_);

   }

   public std_msgs.msg.dds.Header getHeader()
   {
      return header_;
   }

   public geometry_msgs.msg.dds.Vector3 getVector()
   {
      return vector_;
   }


}