/*
 * This class was automatically generated by jros2
 */
package rosgraph_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class Clock implements ROS2Message<Clock>
{
   public static final java.lang.String name = "rosgraph_msgs::msg::dds_::Clock_";

   public Clock()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(Clock from)
   {
   }

}