/*
 * This class was automatically generated by jros2
 */
package rcl_interfaces.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   These types correspond to the value that is set in the ParameterValue message.
*/
public class ParameterType implements ROS2Message<ParameterType>
{
   public static final java.lang.String name = "rcl_interfaces::msg::dds_::ParameterType_";

   /**
      Default value, which implies this is not a valid parameter.
   */
   public static final byte PARAMETER_NOT_SET = 0;
   public static final byte PARAMETER_BOOL = 1;
   public static final byte PARAMETER_INTEGER = 2;
   public static final byte PARAMETER_DOUBLE = 3;
   public static final byte PARAMETER_STRING = 4;
   public static final byte PARAMETER_BYTE_ARRAY = 5;
   public static final byte PARAMETER_BOOL_ARRAY = 6;
   public static final byte PARAMETER_INTEGER_ARRAY = 7;
   public static final byte PARAMETER_DOUBLE_ARRAY = 8;
   public static final byte PARAMETER_STRING_ARRAY = 9;

   public ParameterType()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(ParameterType from)
   {
   }

}