/*
 * This class was automatically generated by jros2
 */
package rcl_interfaces.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   This message contains descriptors of a parameter event.
   It was an atomic update.
   A specific parameter name can only be in one of the three sets.
*/
public class ParameterEventDescriptors implements ROS2Message<ParameterEventDescriptors>
{
   public static final java.lang.String name = "rcl_interfaces::msg::dds_::ParameterEventDescriptors_";

   private rcl_interfaces.msg.dds.ParameterDescriptor new_parameters_;
   private rcl_interfaces.msg.dds.ParameterDescriptor changed_parameters_;
   private rcl_interfaces.msg.dds.ParameterDescriptor deleted_parameters_;

   public ParameterEventDescriptors()
   {
      new_parameters_ = new rcl_interfaces.msg.dds.ParameterDescriptor();
      changed_parameters_ = new rcl_interfaces.msg.dds.ParameterDescriptor();
      deleted_parameters_ = new rcl_interfaces.msg.dds.ParameterDescriptor();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(ParameterEventDescriptors from)
   {
   }

   public rcl_interfaces.msg.dds.ParameterDescriptor getnew_parameters()
   {
      return new_parameters_;
   }

   public rcl_interfaces.msg.dds.ParameterDescriptor getchanged_parameters()
   {
      return changed_parameters_;
   }

   public rcl_interfaces.msg.dds.ParameterDescriptor getdeleted_parameters()
   {
      return deleted_parameters_;
   }


}