/*
 * This class was automatically generated by jros2
 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   A specification of a polygon where the first and last points are assumed to be connected
*/
public class Polygon implements ROS2Message<Polygon>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::Polygon_";

   private geometry_msgs.msg.dds.Point32 points_;

   public Polygon()
   {
      points_ = new geometry_msgs.msg.dds.Point32();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(Polygon from)
   {
   }

   public geometry_msgs.msg.dds.Point32 getpoints()
   {
      return points_;
   }


}