/*
 * This class was automatically generated by jros2
 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   This represents an orientation with reference coordinate frame and timestamp.
*/
public class QuaternionStamped implements ROS2Message<QuaternionStamped>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::QuaternionStamped_";

   private final std_msgs.msg.dds.Header header_;
   private final geometry_msgs.msg.dds.Quaternion quaternion_;

   public QuaternionStamped()
   {
      header_ = new std_msgs.msg.dds.Header();
      quaternion_ = new geometry_msgs.msg.dds.Quaternion();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(QuaternionStamped from)
   {
   }

   public std_msgs.msg.dds.Header getheader()
   {
      return header_;
   }

   public geometry_msgs.msg.dds.Quaternion getquaternion()
   {
      return quaternion_;
   }


}