/*
 * This class was automatically generated by jros2
 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   This expresses velocity in free space with uncertainty.
*/
public class TwistWithCovariance implements ROS2Message<TwistWithCovariance>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::TwistWithCovariance_";

   private geometry_msgs.msg.dds.Twist twist_;
   /**
      Row-major representation of the 6x6 covariance matrix
      The orientation parameters use a fixed-axis representation.
      In order, the parameters are:
      (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
   */
   private double[] covariance_;

   public TwistWithCovariance()
   {
      twist_ = new geometry_msgs.msg.dds.Twist();
      covariance_ = new double[36];

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += (36 * 8) + CDRBuffer.alignment(currentAlignment, (36 * 8)); // covariance_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      for (int i = 0; i < covariance_.length; ++i)
      {
         buffer.writeDouble(covariance_[i]);
      }

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      for (int i = 0; i < covariance_.length; ++i)
      {
      covariance_[i] = buffer.readDouble();
      }

   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(TwistWithCovariance from)
   {
      for (int i = 0; i < covariance_.length; ++i)
      {
         covariance_[i] = from.covariance_[i];
      }

   }

   public geometry_msgs.msg.dds.Twist gettwist()
   {
      return twist_;
   }

   public double[] getcovariance()
   {
      return covariance_;
   }


}