/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package example_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (example_interfaces/AddTwoInts_Response):
<pre>{@code
int64 sum}</pre>
*/
public class AddTwoInts_Response implements ROS2Message<AddTwoInts_Response>
{
   public static final java.lang.String name = "example_interfaces::msg::dds_::AddTwoIntsResponse_";

   private long sum_;

   public AddTwoInts_Response()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sum_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sum_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sum_ = buffer.readLong();

   }

   @Override
   public void set(AddTwoInts_Response from)
   {
      sum_ = from.sum_;

   }

   public long getSum()
   {
      return sum_;
   }

   public void setSum(long sum_)
   {
      this.sum_ = sum_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("AddTwoInts_Response {");
      builder.append("sum_=");
      builder.append(sum_);

      builder.append("}");
      return builder.toString();
   }
}
