/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package example_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (example_interfaces/AddTwoInts_Request):
<pre>{@code
int64 a
int64 b}</pre>
*/
public class AddTwoInts_Request implements ROS2Message<AddTwoInts_Request>
{
   public static final java.lang.String name = "example_interfaces::msg::dds_::AddTwoIntsRequest_";

   private long a_;
   private long b_;

   public AddTwoInts_Request()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // a_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // b_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(a_);
      buffer.writeLong(b_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      a_ = buffer.readLong();
      b_ = buffer.readLong();

   }

   @Override
   public void set(AddTwoInts_Request from)
   {
      a_ = from.a_;
      b_ = from.b_;

   }

   public long getA()
   {
      return a_;
   }

   public void setA(long a_)
   {
      this.a_ = a_;
   }

   public long getB()
   {
      return b_;
   }

   public void setB(long b_)
   {
      this.b_ = b_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("AddTwoInts_Request {");
      builder.append("a_=");
      builder.append(a_);
      builder.append("b_=");
      builder.append(b_);

      builder.append("}");
      return builder.toString();
   }
}
