/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package example_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Please look at the MultiArrayLayout message definition for
documentation on all multiarrays.
<p>Source (example_interfaces/ByteMultiArray):
<pre>{@code
# This is an example of using complex datatypes.
# It is not recommended to use directly.
# To use a similar datastruct please define a custom message with appropriate semantic meaning.

# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
byte[]            data          # array of data
}</pre>
*/
public class ByteMultiArray implements ROS2Message<ByteMultiArray>
{
   public static final java.lang.String name = "example_interfaces::msg::dds_::ByteMultiArray_";

   private final example_interfaces.MultiArrayLayout layout_; // specification of data layout
   private final IDLByteSequence data_; // array of data

   public ByteMultiArray()
   {
      layout_ = new example_interfaces.MultiArrayLayout();
      data_ = new IDLByteSequence();

   }

   public ByteMultiArray(ByteMultiArray from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += layout_.calculateSizeBytes(currentAlignment);
      currentAlignment += data_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      layout_.serialize(buffer);
      data_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      layout_.deserialize(buffer);
      data_.deserialize(buffer);

   }

   @Override
   public void set(ByteMultiArray from)
   {
      layout_.set(from.layout_);
      data_.set(from.data_);

   }

   public example_interfaces.MultiArrayLayout getLayout()
   {
      return layout_;
   }

   public IDLByteSequence getData()
   {
      return data_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ByteMultiArray {");
      builder.append("layout_=");
      builder.append(layout_);
      builder.append("data_=");
      builder.append(data_);

      builder.append("}");
      return builder.toString();
   }
}