/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package example_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (example_interfaces/Int8):
<pre>{@code
# This is an example message of using a primitive datatype, in8.
# If you want to test with this that's fine, but if you are deploying
# it into a system you should create a semantically meaningful message type.
# If you want to embed it in another message, use the primitive data type instead.
int8 data
}</pre>
*/
public class Int8 implements ROS2Message<Int8>
{
   public static final java.lang.String name = "example_interfaces::msg::dds_::Int8_";

   /**
      This is an example message of using a primitive datatype, in8.
      If you want to test with this that's fine, but if you are deploying
      it into a system you should create a semantically meaningful message type.
      If you want to embed it in another message, use the primitive data type instead.
   */
   private byte data_;

   public Int8()
   {
   }

   public Int8(Int8 from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // data_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(data_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      data_ = buffer.readByte();

   }

   @Override
   public void set(Int8 from)
   {
      data_ = from.data_;

   }

   public byte getData()
   {
      return data_;
   }

   public void setData(byte data_)
   {
      this.data_ = data_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Int8 {");
      builder.append("data_=");
      builder.append(data_);

      builder.append("}");
      return builder.toString();
   }
}