/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package example_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (example_interfaces/SetBool_Response):
<pre>{@code
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages}</pre>
*/
public class SetBool_Response implements ROS2Message<SetBool_Response>
{
   public static final java.lang.String name = "example_interfaces::msg::dds_::SetBoolResponse_";

   private boolean success_; // indicate successful run of triggered service
   private final StringBuilder message_; // informational, e.g. for error messages

   public SetBool_Response()
   {
      success_ = (boolean) false;
      message_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // success_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (2 * message_.length()) + 1; // message_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(success_);
      buffer.writeString(message_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      success_ = buffer.readBoolean();
      buffer.readString(message_);

   }

   @Override
   public void set(SetBool_Response from)
   {
      success_ = from.success_;
      message_.delete(0, message_.length());
      message_.insert(0, from.message_);

   }

   public boolean getSuccess()
   {
      return success_;
   }

   public void setSuccess(boolean success_)
   {
      this.success_ = success_;
   }

   public StringBuilder getMessage()
   {
      return message_;
   }

   public java.lang.String getMessageAsString()
   {
      return message_.toString();
   }

   public void setMessage(java.lang.String s)
   {
      this.message_.delete(0, this.message_.length());
      this.message_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("SetBool_Response {");
      builder.append("success_=");
      builder.append(success_);
      builder.append("message_=");
      builder.append(message_.toString());

      builder.append("}");
      return builder.toString();
   }
}
