/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package example_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (example_interfaces/UInt8):
<pre>{@code
# This is an example message of using a primitive datatype, uint8.
# If you want to test with this that's fine, but if you are deploying
# it into a system you should create a semantically meaningful message type.
# If you want to embed it in another message, use the primitive data type instead.
uint8 data
}</pre>
*/
public class UInt8 implements ROS2Message<UInt8>
{
   public static final java.lang.String name = "example_interfaces::msg::dds_::UInt8_";

   /**
      This is an example message of using a primitive datatype, uint8.
      If you want to test with this that's fine, but if you are deploying
      it into a system you should create a semantically meaningful message type.
      If you want to embed it in another message, use the primitive data type instead.
   */
   private short data_;

   public UInt8()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // data_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeShort(data_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      data_ = buffer.readShort();

   }

   @Override
   public void set(UInt8 from)
   {
      data_ = from.data_;

   }

   public short getData()
   {
      return data_;
   }

   public void setData(short data_)
   {
      this.data_ = data_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("UInt8 {");
      builder.append("data_=");
      builder.append(data_);

      builder.append("}");
      return builder.toString();
   }
}