/*
 * This class was automatically generated by jros2
 */
package shape_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
    Definition of a triangle's vertices.
*/
public class MeshTriangle implements ROS2Message<MeshTriangle>
{
   public static final String name = "shape_msgs::msg::dds_::MeshTriangle_";

   private int[] vertex_indices_;

   public MeshTriangle()
   {
      vertex_indices_ = new int[3];

   }

   public int[] getvertex_indices()
   {
      return vertex_indices_;
   }


   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += (3 * 4) + CDRBuffer.alignment(currentAlignment, (3 * 4)); // vertex_indices_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      for (int i = 0; i < vertex_indices_.length; ++i)
      {
         buffer.writeInt(vertex_indices_[i]);
      }

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      for (int i = 0; i < vertex_indices_.length; ++i)
      {
         vertex_indices_[i] = buffer.readInt();
      }

   }

   @Override
   public String getName()
   {
      return name;
   }

   @Override
   public void set(MeshTriangle from)
   {
      for (int i = 0; i < vertex_indices_.length; ++i)
      {
         vertex_indices_[i] = from.vertex_indices_[i];
      }

   }
}