/*
 * This class was automatically generated by jros2
 */
package nav_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   An array of poses that represents a Path for a robot to follow.
*/
public class Path implements ROS2Message<Path>
{
   public static final java.lang.String name = "nav_msgs::msg::dds_::Path_";

   /**
      Indicates the frame_id of the path.
   */
   private std_msgs.msg.dds.Header header_;
   /**
      Array of poses to follow.
   */
   private geometry_msgs.msg.dds.PoseStamped poses_;

   public Path()
   {
      poses_ = new geometry_msgs.msg.dds.PoseStamped();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(Path from)
   {
   }

   public std_msgs.msg.dds.Header getheader()
   {
      return header_;
   }

   public geometry_msgs.msg.dds.PoseStamped getposes()
   {
      return poses_;
   }


}