/*
 * This class was automatically generated by jros2
 */
package nav_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
*/
public class Path implements ROS2Message<Path>
{
   public static final String name = "nav_msgs::msg::dds_::Path_";

   public Path()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public String getName()
   {
      return name;
   }

   @Override
   public void set(Path from)
   {
   }
}