/*
 * This class was automatically generated by jros2
 */
package rcl_interfaces.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   This is the message to communicate a parameter. It is an open struct with an enum in
   the descriptor to select which value is active.
*/
public class Parameter implements ROS2Message<Parameter>
{
   public static final java.lang.String name = "rcl_interfaces::msg::dds_::Parameter_";

   /**
      The full name of the parameter.
   */
   private StringBuilder name_;
   /**
      The parameter's value which can be one of several types, see
      `ParameterValue.msg` and `ParameterType.msg`.
   */
   private rcl_interfaces.msg.dds.ParameterValue value_;

   public Parameter()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += -1 + CDRBuffer.alignment(currentAlignment, -1); // name_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(name_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(name_);

   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(Parameter from)
   {
      name_ = from.name_;

   }

   public StringBuilder getname()
   {
      return name_;
   }

   public void setname(StringBuilder name_)
   {
      this.name_ = name_;
   }

   public rcl_interfaces.msg.dds.ParameterValue getvalue()
   {
      return value_;
   }


}