/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package std_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (std_msgs/Empty):
<pre>{@code
}</pre>
*/
public class Empty implements ROS2Message<Empty>
{
   public static final java.lang.String name = "std_msgs::msg::dds_::Empty_";

   public Empty()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public void set(Empty from)
   {
   }

}