/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package my_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (my_interfaces/MyPoint3DList):
<pre>{@code
sensor_msgs/Image s
my_interfaces/MyPoint3D[] point_list}</pre>
*/
public class MyPoint3DList implements ROS2Message<MyPoint3DList>
{
   public static final java.lang.String name = "my_interfaces::msg::dds_::MyPoint3DList_";

   private final sensor_msgs.Image s_;
   private final IDLObjectSequence<us.ihmc.MyPoint3DMessage> point_list_;

   public MyPoint3DList()
   {
      s_ = new sensor_msgs.Image();
      point_list_ = new IDLObjectSequence<us.ihmc.MyPoint3DMessage>(us.ihmc.MyPoint3DMessage.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += s_.calculateSizeBytes(currentAlignment);
      currentAlignment += point_list_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      s_.serialize(buffer);
      point_list_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      s_.deserialize(buffer);
      point_list_.deserialize(buffer);

   }

   @Override
   public void set(MyPoint3DList from)
   {
      s_.set(from.s_);
      point_list_.set(from.point_list_);

   }

   public sensor_msgs.Image getS()
   {
      return s_;
   }

   public IDLObjectSequence<us.ihmc.MyPoint3DMessage> getPointList()
   {
      return point_list_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("MyPoint3DList {");
      builder.append("s_=");
      builder.append(s_);
      builder.append("point_list_=");
      builder.append(point_list_);

      builder.append("}");
      return builder.toString();
   }
}