/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package rmw_dds_common;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (rmw_dds_common/NodeEntitiesInfo):
<pre>{@code
string<=256 node_namespace
string<=256 node_name
Gid[] reader_gid_seq
Gid[] writer_gid_seq
}</pre>
*/
public class NodeEntitiesInfo implements ROS2Message<NodeEntitiesInfo>
{
   public static final java.lang.String name = "rmw_dds_common::msg::dds_::NodeEntitiesInfo_";

   // Note: The length of this string should not exceed 256 characters.
   // This is not strictly enforced in Java / jros2.
   private final StringBuilder node_namespace_;
   // Note: The length of this string should not exceed 256 characters.
   // This is not strictly enforced in Java / jros2.
   private final StringBuilder node_name_;
   private final IDLObjectSequence<rmw_dds_common.Gid> reader_gid_seq_;
   private final IDLObjectSequence<rmw_dds_common.Gid> writer_gid_seq_;

   public NodeEntitiesInfo()
   {
      node_namespace_ = new StringBuilder(256);
      node_name_ = new StringBuilder(256);
      reader_gid_seq_ = new IDLObjectSequence<rmw_dds_common.Gid>(rmw_dds_common.Gid.class);
      writer_gid_seq_ = new IDLObjectSequence<rmw_dds_common.Gid>(rmw_dds_common.Gid.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * (node_namespace_.length() + 1)); // node_namespace_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * (node_name_.length() + 1)); // node_name_
      currentAlignment += reader_gid_seq_.calculateSizeBytes(currentAlignment);
      currentAlignment += writer_gid_seq_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(node_namespace_);
      buffer.writeString(node_name_);
      reader_gid_seq_.serialize(buffer);
      writer_gid_seq_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(node_namespace_);
      buffer.readString(node_name_);
      reader_gid_seq_.deserialize(buffer);
      writer_gid_seq_.deserialize(buffer);

   }

   @Override
   public void set(NodeEntitiesInfo from)
   {
      node_namespace_.delete(0, node_namespace_.length());
      node_namespace_.insert(0, from.node_namespace_);
      node_name_.delete(0, node_name_.length());
      node_name_.insert(0, from.node_name_);
      reader_gid_seq_.set(from.reader_gid_seq_);
      writer_gid_seq_.set(from.writer_gid_seq_);

   }

   public StringBuilder getNodeNamespace()
   {
      return node_namespace_;
   }

   public java.lang.String getNodeNamespaceAsString()
   {
      return node_namespace_.toString();
   }

   public void setNodeNamespace(java.lang.String s)
   {
      this.node_namespace_.delete(0, this.node_namespace_.length());
      this.node_namespace_.insert(0, s);
   }
   public StringBuilder getNodeName()
   {
      return node_name_;
   }

   public java.lang.String getNodeNameAsString()
   {
      return node_name_.toString();
   }

   public void setNodeName(java.lang.String s)
   {
      this.node_name_.delete(0, this.node_name_.length());
      this.node_name_.insert(0, s);
   }
   public IDLObjectSequence<rmw_dds_common.Gid> getReaderGidSeq()
   {
      return reader_gid_seq_;
   }

   public IDLObjectSequence<rmw_dds_common.Gid> getWriterGidSeq()
   {
      return writer_gid_seq_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("NodeEntitiesInfo {");
      builder.append("node_namespace_=");
      builder.append(node_namespace_.toString());
      builder.append("node_name_=");
      builder.append(node_name_.toString());
      builder.append("reader_gid_seq_=");
      builder.append(reader_gid_seq_);
      builder.append("writer_gid_seq_=");
      builder.append(writer_gid_seq_);

      builder.append("}");
      return builder.toString();
   }
}