/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package visualization_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (visualization_msgs/GetInteractiveMarkers_Response):
<pre>{@code
# Sequence number.
# Set to the sequence number of the latest update message
# at the time the server received the request.
# Clients use this to detect if any updates were missed.
uint64 sequence_number

# All interactive markers provided by the server.
InteractiveMarker[] markers}</pre>
*/
public class GetInteractiveMarkers_Response implements ROS2Message<GetInteractiveMarkers_Response>
{
   public static final java.lang.String name = "visualization_msgs::msg::dds_::GetInteractiveMarkersResponse_";

   /**
      Sequence number.
      Set to the sequence number of the latest update message
      at the time the server received the request.
      Clients use this to detect if any updates were missed.
   */
   private long sequence_number_;
   /**
      All interactive markers provided by the server.
   */
   private final IDLObjectSequence<visualization_msgs.InteractiveMarker> markers_;

   public GetInteractiveMarkers_Response()
   {
      markers_ = new IDLObjectSequence<visualization_msgs.InteractiveMarker>(visualization_msgs.InteractiveMarker.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_number_
      currentAlignment += markers_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_number_);
      markers_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_number_ = buffer.readLong();
      markers_.deserialize(buffer);

   }

   @Override
   public void set(GetInteractiveMarkers_Response from)
   {
      sequence_number_ = from.sequence_number_;
      markers_.set(from.markers_);

   }

   public long getSequenceNumber()
   {
      return sequence_number_;
   }

   public void setSequenceNumber(long sequence_number_)
   {
      this.sequence_number_ = sequence_number_;
   }

   public IDLObjectSequence<visualization_msgs.InteractiveMarker> getMarkers()
   {
      return markers_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("GetInteractiveMarkers_Response {");
      builder.append("sequence_number_=");
      builder.append(sequence_number_);
      builder.append("markers_=");
      builder.append(markers_);

      builder.append("}");
      return builder.toString();
   }
}
