/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package visualization_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (visualization_msgs/InteractiveMarkerPose):
<pre>{@code

# Time/frame info.
std_msgs/Header header

# Initial pose. Also, defines the pivot point for rotations.
geometry_msgs/Pose pose

# Identifying string. Must be globally unique in
# the topic that this message is sent through.
string name
}</pre>
*/
public class InteractiveMarkerPose implements ROS2Message<InteractiveMarkerPose>
{
   public static final java.lang.String name = "visualization_msgs::msg::dds_::InteractiveMarkerPose_";

   /**
      Time/frame info.
   */
   private final std_msgs.Header header_;
   /**
      Initial pose. Also, defines the pivot point for rotations.
   */
   private final geometry_msgs.Pose pose_;
   /**
      Identifying string. Must be globally unique in
      the topic that this message is sent through.
   */
   private final StringBuilder name_;

   public InteractiveMarkerPose()
   {
      header_ = new std_msgs.Header();
      pose_ = new geometry_msgs.Pose();
      name_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += pose_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (2 * (name_.length() + 1)); // name_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      pose_.serialize(buffer);
      buffer.writeString(name_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      pose_.deserialize(buffer);
      buffer.readString(name_);

   }

   @Override
   public void set(InteractiveMarkerPose from)
   {
      header_.set(from.header_);
      pose_.set(from.pose_);
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public geometry_msgs.Pose getPose()
   {
      return pose_;
   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("InteractiveMarkerPose {");
      builder.append("header_=");
      builder.append(header_);
      builder.append("pose_=");
      builder.append(pose_);
      builder.append("name_=");
      builder.append(name_.toString());

      builder.append("}");
      return builder.toString();
   }
}