/*
 * This class was automatically generated by jros2
 */
package actionlib_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class GoalStatus implements ROS2Message<GoalStatus>
{
   public static final String name = "actionlib_msgs::msg::dds_::GoalStatus_";

   private actionlib_msgs.msg.dds.GoalID goal_id_;
   private byte status_;
   /**
       Allow for the user to associate a string with GoalStatus for debugging.
   */
   private StringBuilder text_;

   public GoalStatus()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // status_
      currentAlignment += -1 + CDRBuffer.alignment(currentAlignment, -1); // text_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(status_);
      buffer.(text_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      status_ = buffer.readByte();
      text_ = buffer.();

   }

   @Override
   public String getName()
   {
      return name;
   }

   @Override
   public void set(GoalStatus from)
   {
      status_ = from.status_;
      text_ = from.text_;

   }

   public actionlib_msgs.msg.dds.GoalID getgoal_id()
   {
      return goal_id_;
   }

   public byte getstatus()
   {
      return status_;
   }

   public void setstatus(byte status_)
   {
      this.status_ = status_;
   }

   public StringBuilder gettext()
   {
      return text_;
   }

   public void settext(StringBuilder text_)
   {
      this.text_ = text_;
   }


}