/*
 * This class was automatically generated by jros2
 */
package actionlib_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class GoalStatusArray implements ROS2Message<GoalStatusArray>
{
   public static final String name = "actionlib_msgs::msg::dds_::GoalStatusArray_";

   private actionlib_msgs.msg.dds.GoalStatus status_list_;

   public GoalStatusArray()
   {
      status_list_ = new actionlib_msgs.msg.dds.GoalStatus();

   }

   public actionlib_msgs.msg.dds.GoalStatus getstatus_list()
   {
      return status_list_;
   }


   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public String getName()
   {
      return name;
   }

   @Override
   public void set(GoalStatusArray from)
   {
   }
}