/*
 * This class was automatically generated by jros2
 */
package actionlib_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
*/
public class GoalID implements ROS2Message<GoalID>
{
   public static final String name = "actionlib_msgs::msg::dds_::GoalID_";

   /**
       The id provides a way to associate feedback and
       result message with specific goal requests. The id
       specified must be unique.
   */
   private StringBuilder id_;

   public GoalID()
   {
   }

   public StringBuilder getid()
   {
      return id_;
   }

   public void setid(StringBuilder id_)
   {
      this.id_ = id_;
   }


   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += -1 + CDRBuffer.alignment(currentAlignment, -1); // id_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.(id_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      id_ = buffer.();

   }

   @Override
   public String getName()
   {
      return name;
   }

   @Override
   public void set(GoalID from)
   {
      id_ = from.id_;

   }
}