/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 *
 * Original .msg file content (example_interfaces/Empty.msg):

# If you want to test with this that's fine, but if you are deploying
# it into a system you should create a semantically meaningful message type.


 */
package example_interfaces.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class Empty implements ROS2Message<Empty>
{
   public static final java.lang.String name = "example_interfaces::msg::dds_::Empty_";

   public Empty()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public void set(Empty from)
   {
   }

}