/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 *
 * Original .msg file content (example_interfaces/UInt64.msg):

# This is an example message of using a primitive datatype, unint64.
# If you want to test with this that's fine, but if you are deploying
# it into a system you should create a semantically meaningful message type.
# If you want to embed it in another message, use the primitive data type instead.
uint64 data


 */
package example_interfaces.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class UInt64 implements ROS2Message<UInt64>
{
   public static final java.lang.String name = "example_interfaces::msg::dds_::UInt64_";

   /**
      This is an example message of using a primitive datatype, unint64.
      If you want to test with this that's fine, but if you are deploying
      it into a system you should create a semantically meaningful message type.
      If you want to embed it in another message, use the primitive data type instead.
   */
   private long data_;

   public UInt64()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // data_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(data_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      data_ = buffer.readLong();

   }

   @Override
   public void set(UInt64 from)
   {
      data_ = from.data_;

   }

   public long getdata()
   {
      return data_;
   }

   public void setdata(long data_)
   {
      this.data_ = data_;
   }


}