/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package sensor_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Constants are chosen to match the enums in the linux kernel
defined in include/linux/power_supply.h as of version 3.7
The one difference is for style reasons the constants are
all uppercase not mixed case.
<p>Source (sensor_msgs/BatteryState):
<pre>{@code

# Constants are chosen to match the enums in the linux kernel
# defined in include/linux/power_supply.h as of version 3.7
# The one difference is for style reasons the constants are
# all uppercase not mixed case.

# Power supply status constants
uint8 POWER_SUPPLY_STATUS_UNKNOWN = 0
uint8 POWER_SUPPLY_STATUS_CHARGING = 1
uint8 POWER_SUPPLY_STATUS_DISCHARGING = 2
uint8 POWER_SUPPLY_STATUS_NOT_CHARGING = 3
uint8 POWER_SUPPLY_STATUS_FULL = 4

# Power supply health constants
uint8 POWER_SUPPLY_HEALTH_UNKNOWN = 0
uint8 POWER_SUPPLY_HEALTH_GOOD = 1
uint8 POWER_SUPPLY_HEALTH_OVERHEAT = 2
uint8 POWER_SUPPLY_HEALTH_DEAD = 3
uint8 POWER_SUPPLY_HEALTH_OVERVOLTAGE = 4
uint8 POWER_SUPPLY_HEALTH_UNSPEC_FAILURE = 5
uint8 POWER_SUPPLY_HEALTH_COLD = 6
uint8 POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE = 7
uint8 POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE = 8

# Power supply technology (chemistry) constants
uint8 POWER_SUPPLY_TECHNOLOGY_UNKNOWN = 0
uint8 POWER_SUPPLY_TECHNOLOGY_NIMH = 1
uint8 POWER_SUPPLY_TECHNOLOGY_LION = 2
uint8 POWER_SUPPLY_TECHNOLOGY_LIPO = 3
uint8 POWER_SUPPLY_TECHNOLOGY_LIFE = 4
uint8 POWER_SUPPLY_TECHNOLOGY_NICD = 5
uint8 POWER_SUPPLY_TECHNOLOGY_LIMN = 6

std_msgs/Header  header
float32 voltage          # Voltage in Volts (Mandatory)
float32 temperature      # Temperature in Degrees Celsius (If unmeasured NaN)
float32 current          # Negative when discharging (A)  (If unmeasured NaN)
float32 charge           # Current charge in Ah  (If unmeasured NaN)
float32 capacity         # Capacity in Ah (last full capacity)  (If unmeasured NaN)
float32 design_capacity  # Capacity in Ah (design capacity)  (If unmeasured NaN)
float32 percentage       # Charge percentage on 0 to 1 range  (If unmeasured NaN)
uint8   power_supply_status     # The charging status as reported. Values defined above
uint8   power_supply_health     # The battery health metric. Values defined above
uint8   power_supply_technology # The battery chemistry. Values defined above
bool    present          # True if the battery is present

float32[] cell_voltage   # An array of individual cell voltages for each cell in the pack
                         # If individual voltages unknown but number of cells known set each to NaN
float32[] cell_temperature # An array of individual cell temperatures for each cell in the pack
                           # If individual temperatures unknown but number of cells known set each to NaN
string location          # The location into which the battery is inserted. (slot number or plug)
string serial_number     # The best approximation of the battery serial number
}</pre>
*/
public class BatteryState implements ROS2Message<BatteryState>
{
   public static final java.lang.String name = "sensor_msgs::msg::dds_::BatteryState_";

   /**
      Power supply status constants
   */
   public static final short POWER_SUPPLY_STATUS_UNKNOWN = 0;
   public static final short POWER_SUPPLY_STATUS_CHARGING = 1;
   public static final short POWER_SUPPLY_STATUS_DISCHARGING = 2;
   public static final short POWER_SUPPLY_STATUS_NOT_CHARGING = 3;
   public static final short POWER_SUPPLY_STATUS_FULL = 4;
   /**
      Power supply health constants
   */
   public static final short POWER_SUPPLY_HEALTH_UNKNOWN = 0;
   public static final short POWER_SUPPLY_HEALTH_GOOD = 1;
   public static final short POWER_SUPPLY_HEALTH_OVERHEAT = 2;
   public static final short POWER_SUPPLY_HEALTH_DEAD = 3;
   public static final short POWER_SUPPLY_HEALTH_OVERVOLTAGE = 4;
   public static final short POWER_SUPPLY_HEALTH_UNSPEC_FAILURE = 5;
   public static final short POWER_SUPPLY_HEALTH_COLD = 6;
   public static final short POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE = 7;
   public static final short POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE = 8;
   /**
      Power supply technology (chemistry) constants
   */
   public static final short POWER_SUPPLY_TECHNOLOGY_UNKNOWN = 0;
   public static final short POWER_SUPPLY_TECHNOLOGY_NIMH = 1;
   public static final short POWER_SUPPLY_TECHNOLOGY_LION = 2;
   public static final short POWER_SUPPLY_TECHNOLOGY_LIPO = 3;
   public static final short POWER_SUPPLY_TECHNOLOGY_LIFE = 4;
   public static final short POWER_SUPPLY_TECHNOLOGY_NICD = 5;
   public static final short POWER_SUPPLY_TECHNOLOGY_LIMN = 6;
   private final std_msgs.Header header_;
   private float voltage_; // Voltage in Volts (Mandatory)
   private float temperature_; // Temperature in Degrees Celsius (If unmeasured NaN)
   private float current_; // Negative when discharging (A)  (If unmeasured NaN)
   private float charge_; // Current charge in Ah  (If unmeasured NaN)
   private float capacity_; // Capacity in Ah (last full capacity)  (If unmeasured NaN)
   private float design_capacity_; // Capacity in Ah (design capacity)  (If unmeasured NaN)
   private float percentage_; // Charge percentage on 0 to 1 range  (If unmeasured NaN)
   private short power_supply_status_; // The charging status as reported. Values defined above
   private short power_supply_health_; // The battery health metric. Values defined above
   private short power_supply_technology_; // The battery chemistry. Values defined above
   private boolean present_; // True if the battery is present
   private final IDLFloatSequence cell_voltage_; // An array of individual cell voltages for each cell in the pack
   /**
      If individual voltages unknown but number of cells known set each to NaN
   */
   private final IDLFloatSequence cell_temperature_; // An array of individual cell temperatures for each cell in the pack
   /**
      If individual temperatures unknown but number of cells known set each to NaN
   */
   private final StringBuilder location_; // The location into which the battery is inserted. (slot number or plug)
   private final StringBuilder serial_number_; // The best approximation of the battery serial number

   public BatteryState()
   {
      header_ = new std_msgs.Header();
      present_ = (boolean) false;
      cell_voltage_ = new IDLFloatSequence();
      cell_temperature_ = new IDLFloatSequence();
      location_ = new StringBuilder();
      serial_number_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // voltage_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // temperature_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // current_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // charge_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // capacity_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // design_capacity_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // percentage_
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // power_supply_status_
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // power_supply_health_
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // power_supply_technology_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // present_
      currentAlignment += cell_voltage_.calculateSizeBytes(currentAlignment);
      currentAlignment += cell_temperature_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * (location_.length() + 1)); // location_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * (serial_number_.length() + 1)); // serial_number_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      buffer.writeFloat(voltage_);
      buffer.writeFloat(temperature_);
      buffer.writeFloat(current_);
      buffer.writeFloat(charge_);
      buffer.writeFloat(capacity_);
      buffer.writeFloat(design_capacity_);
      buffer.writeFloat(percentage_);
      buffer.writeShort(power_supply_status_);
      buffer.writeShort(power_supply_health_);
      buffer.writeShort(power_supply_technology_);
      buffer.writeBoolean(present_);
      cell_voltage_.serialize(buffer);
      cell_temperature_.serialize(buffer);
      buffer.writeString(location_);
      buffer.writeString(serial_number_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      voltage_ = buffer.readFloat();
      temperature_ = buffer.readFloat();
      current_ = buffer.readFloat();
      charge_ = buffer.readFloat();
      capacity_ = buffer.readFloat();
      design_capacity_ = buffer.readFloat();
      percentage_ = buffer.readFloat();
      power_supply_status_ = buffer.readShort();
      power_supply_health_ = buffer.readShort();
      power_supply_technology_ = buffer.readShort();
      present_ = buffer.readBoolean();
      cell_voltage_.deserialize(buffer);
      cell_temperature_.deserialize(buffer);
      buffer.readString(location_);
      buffer.readString(serial_number_);

   }

   @Override
   public void set(BatteryState from)
   {
      header_.set(from.header_);
      voltage_ = from.voltage_;
      temperature_ = from.temperature_;
      current_ = from.current_;
      charge_ = from.charge_;
      capacity_ = from.capacity_;
      design_capacity_ = from.design_capacity_;
      percentage_ = from.percentage_;
      power_supply_status_ = from.power_supply_status_;
      power_supply_health_ = from.power_supply_health_;
      power_supply_technology_ = from.power_supply_technology_;
      present_ = from.present_;
      cell_voltage_.set(from.cell_voltage_);
      cell_temperature_.set(from.cell_temperature_);
      location_.delete(0, location_.length());
      location_.insert(0, from.location_);
      serial_number_.delete(0, serial_number_.length());
      serial_number_.insert(0, from.serial_number_);

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public float getVoltage()
   {
      return voltage_;
   }

   public void setVoltage(float voltage_)
   {
      this.voltage_ = voltage_;
   }

   public float getTemperature()
   {
      return temperature_;
   }

   public void setTemperature(float temperature_)
   {
      this.temperature_ = temperature_;
   }

   public float getCurrent()
   {
      return current_;
   }

   public void setCurrent(float current_)
   {
      this.current_ = current_;
   }

   public float getCharge()
   {
      return charge_;
   }

   public void setCharge(float charge_)
   {
      this.charge_ = charge_;
   }

   public float getCapacity()
   {
      return capacity_;
   }

   public void setCapacity(float capacity_)
   {
      this.capacity_ = capacity_;
   }

   public float getDesignCapacity()
   {
      return design_capacity_;
   }

   public void setDesignCapacity(float design_capacity_)
   {
      this.design_capacity_ = design_capacity_;
   }

   public float getPercentage()
   {
      return percentage_;
   }

   public void setPercentage(float percentage_)
   {
      this.percentage_ = percentage_;
   }

   public short getPowerSupplyStatus()
   {
      return power_supply_status_;
   }

   public void setPowerSupplyStatus(short power_supply_status_)
   {
      this.power_supply_status_ = power_supply_status_;
   }

   public short getPowerSupplyHealth()
   {
      return power_supply_health_;
   }

   public void setPowerSupplyHealth(short power_supply_health_)
   {
      this.power_supply_health_ = power_supply_health_;
   }

   public short getPowerSupplyTechnology()
   {
      return power_supply_technology_;
   }

   public void setPowerSupplyTechnology(short power_supply_technology_)
   {
      this.power_supply_technology_ = power_supply_technology_;
   }

   public boolean getPresent()
   {
      return present_;
   }

   public void setPresent(boolean present_)
   {
      this.present_ = present_;
   }

   public IDLFloatSequence getCellVoltage()
   {
      return cell_voltage_;
   }

   public IDLFloatSequence getCellTemperature()
   {
      return cell_temperature_;
   }

   public StringBuilder getLocation()
   {
      return location_;
   }

   public java.lang.String getLocationAsString()
   {
      return location_.toString();
   }

   public void setLocation(java.lang.String s)
   {
      this.location_.delete(0, this.location_.length());
      this.location_.insert(0, s);
   }
   public StringBuilder getSerialNumber()
   {
      return serial_number_;
   }

   public java.lang.String getSerialNumberAsString()
   {
      return serial_number_.toString();
   }

   public void setSerialNumber(java.lang.String s)
   {
      this.serial_number_.delete(0, this.serial_number_.length());
      this.serial_number_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("BatteryState {");
      builder.append("POWER_SUPPLY_STATUS_UNKNOWN=");
      builder.append(POWER_SUPPLY_STATUS_UNKNOWN);
      builder.append("POWER_SUPPLY_STATUS_CHARGING=");
      builder.append(POWER_SUPPLY_STATUS_CHARGING);
      builder.append("POWER_SUPPLY_STATUS_DISCHARGING=");
      builder.append(POWER_SUPPLY_STATUS_DISCHARGING);
      builder.append("POWER_SUPPLY_STATUS_NOT_CHARGING=");
      builder.append(POWER_SUPPLY_STATUS_NOT_CHARGING);
      builder.append("POWER_SUPPLY_STATUS_FULL=");
      builder.append(POWER_SUPPLY_STATUS_FULL);
      builder.append("POWER_SUPPLY_HEALTH_UNKNOWN=");
      builder.append(POWER_SUPPLY_HEALTH_UNKNOWN);
      builder.append("POWER_SUPPLY_HEALTH_GOOD=");
      builder.append(POWER_SUPPLY_HEALTH_GOOD);
      builder.append("POWER_SUPPLY_HEALTH_OVERHEAT=");
      builder.append(POWER_SUPPLY_HEALTH_OVERHEAT);
      builder.append("POWER_SUPPLY_HEALTH_DEAD=");
      builder.append(POWER_SUPPLY_HEALTH_DEAD);
      builder.append("POWER_SUPPLY_HEALTH_OVERVOLTAGE=");
      builder.append(POWER_SUPPLY_HEALTH_OVERVOLTAGE);
      builder.append("POWER_SUPPLY_HEALTH_UNSPEC_FAILURE=");
      builder.append(POWER_SUPPLY_HEALTH_UNSPEC_FAILURE);
      builder.append("POWER_SUPPLY_HEALTH_COLD=");
      builder.append(POWER_SUPPLY_HEALTH_COLD);
      builder.append("POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE=");
      builder.append(POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE);
      builder.append("POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE=");
      builder.append(POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE);
      builder.append("POWER_SUPPLY_TECHNOLOGY_UNKNOWN=");
      builder.append(POWER_SUPPLY_TECHNOLOGY_UNKNOWN);
      builder.append("POWER_SUPPLY_TECHNOLOGY_NIMH=");
      builder.append(POWER_SUPPLY_TECHNOLOGY_NIMH);
      builder.append("POWER_SUPPLY_TECHNOLOGY_LION=");
      builder.append(POWER_SUPPLY_TECHNOLOGY_LION);
      builder.append("POWER_SUPPLY_TECHNOLOGY_LIPO=");
      builder.append(POWER_SUPPLY_TECHNOLOGY_LIPO);
      builder.append("POWER_SUPPLY_TECHNOLOGY_LIFE=");
      builder.append(POWER_SUPPLY_TECHNOLOGY_LIFE);
      builder.append("POWER_SUPPLY_TECHNOLOGY_NICD=");
      builder.append(POWER_SUPPLY_TECHNOLOGY_NICD);
      builder.append("POWER_SUPPLY_TECHNOLOGY_LIMN=");
      builder.append(POWER_SUPPLY_TECHNOLOGY_LIMN);
      builder.append("header_=");
      builder.append(header_);
      builder.append("voltage_=");
      builder.append(voltage_);
      builder.append("temperature_=");
      builder.append(temperature_);
      builder.append("current_=");
      builder.append(current_);
      builder.append("charge_=");
      builder.append(charge_);
      builder.append("capacity_=");
      builder.append(capacity_);
      builder.append("design_capacity_=");
      builder.append(design_capacity_);
      builder.append("percentage_=");
      builder.append(percentage_);
      builder.append("power_supply_status_=");
      builder.append(power_supply_status_);
      builder.append("power_supply_health_=");
      builder.append(power_supply_health_);
      builder.append("power_supply_technology_=");
      builder.append(power_supply_technology_);
      builder.append("present_=");
      builder.append(present_);
      builder.append("cell_voltage_=");
      builder.append(cell_voltage_);
      builder.append("cell_temperature_=");
      builder.append(cell_temperature_);
      builder.append("location_=");
      builder.append(location_.toString());
      builder.append("serial_number_=");
      builder.append(serial_number_.toString());

      builder.append("}");
      return builder.toString();
   }
}