/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package sensor_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Measurement of the Magnetic Field vector at a specific location.

If the covariance of the measurement is known, it should be filled in.
If all you know is the variance of each measurement, e.g. from the datasheet,
just put those along the diagonal.
A covariance matrix of all zeros will be interpreted as "covariance unknown",
and to use the data a covariance will have to be assumed or gotten from some
other source.
<p>Source (sensor_msgs/MagneticField):
<pre>{@code
# Measurement of the Magnetic Field vector at a specific location.
#
# If the covariance of the measurement is known, it should be filled in.
# If all you know is the variance of each measurement, e.g. from the datasheet,
# just put those along the diagonal.
# A covariance matrix of all zeros will be interpreted as "covariance unknown",
# and to use the data a covariance will have to be assumed or gotten from some
# other source.

std_msgs/Header header               # timestamp is the time the
                                           # field was measured
                                           # frame_id is the location and orientation
                                           # of the field measurement

geometry_msgs/Vector3 magnetic_field # x, y, and z components of the
                                           # field vector in Tesla
                                           # If your sensor does not output 3 axes,
                                           # put NaNs in the components not reported.

float64[9] magnetic_field_covariance       # Row major about x, y, z axes
                                           # 0 is interpreted as variance unknown}</pre>
*/
public class MagneticField implements ROS2Message<MagneticField>
{
   public static final java.lang.String name = "sensor_msgs::msg::dds_::MagneticField_";

   private final std_msgs.Header header_; // timestamp is the time the
   private final geometry_msgs.Vector3 magnetic_field_; // x, y, and z components of the
   private final double[] magnetic_field_covariance_; // Row major about x, y, z axes

   public MagneticField()
   {
      header_ = new std_msgs.Header();
      magnetic_field_ = new geometry_msgs.Vector3();
      magnetic_field_covariance_ = new double[9];

   }

   public MagneticField(MagneticField from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += magnetic_field_.calculateSizeBytes(currentAlignment);
      currentAlignment += (9 * 8) + CDRBuffer.alignment(currentAlignment, (9 * 8)); // magnetic_field_covariance_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      magnetic_field_.serialize(buffer);
      for (int i = 0; i < magnetic_field_covariance_.length; ++i)
      {
         buffer.writeDouble(magnetic_field_covariance_[i]);
      }

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      magnetic_field_.deserialize(buffer);
      for (int i = 0; i < magnetic_field_covariance_.length; ++i)
      {
         magnetic_field_covariance_[i] = buffer.readDouble();
      }

   }

   @Override
   public void set(MagneticField from)
   {
      header_.set(from.header_);
      magnetic_field_.set(from.magnetic_field_);
      for (int i = 0; i < magnetic_field_covariance_.length; ++i)
      {
         magnetic_field_covariance_[i] = from.magnetic_field_covariance_[i];
      }

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public geometry_msgs.Vector3 getMagneticField()
   {
      return magnetic_field_;
   }

   public double[] getMagneticFieldCovariance()
   {
      return magnetic_field_covariance_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("MagneticField {");
      builder.append("header_=");
      builder.append(header_);
      builder.append("magnetic_field_=");
      builder.append(magnetic_field_);
      builder.append("magnetic_field_covariance_=");
      builder.append(java.util.Arrays.toString(magnetic_field_covariance_));

      builder.append("}");
      return builder.toString();
   }
}