/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package sensor_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (sensor_msgs/SetCameraInfo_Response):
<pre>{@code
bool success                             # True if the call succeeded
string status_message                    # Used to give details about success}</pre>
*/
public class SetCameraInfo_Response implements ROS2Message<SetCameraInfo_Response>
{
   public static final java.lang.String name = "sensor_msgs::msg::dds_::SetCameraInfoResponse_";

   private boolean success_; // True if the call succeeded
   private final StringBuilder status_message_; // Used to give details about success

   public SetCameraInfo_Response()
   {
      success_ = (boolean) false;
      status_message_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // success_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (2 * status_message_.length()) + 1; // status_message_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(success_);
      buffer.writeString(status_message_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      success_ = buffer.readBoolean();
      buffer.readString(status_message_);

   }

   @Override
   public void set(SetCameraInfo_Response from)
   {
      success_ = from.success_;
      status_message_.delete(0, status_message_.length());
      status_message_.insert(0, from.status_message_);

   }

   public boolean getSuccess()
   {
      return success_;
   }

   public void setSuccess(boolean success_)
   {
      this.success_ = success_;
   }

   public StringBuilder getStatusMessage()
   {
      return status_message_;
   }

   public java.lang.String getStatusMessageAsString()
   {
      return status_message_.toString();
   }

   public void setStatusMessage(java.lang.String s)
   {
      this.status_message_.delete(0, this.status_message_.length());
      this.status_message_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("SetCameraInfo_Response {");
      builder.append("success_=");
      builder.append(success_);
      builder.append("status_message_=");
      builder.append(status_message_.toString());

      builder.append("}");
      return builder.toString();
   }
}
