/*
 * This class was automatically generated by jros2
 */
package std_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
    This was originally provided as an example message.
    It is deprecated as of Foxy
    It is recommended to create your own semantically meaningful message.
    However if you would like to continue using this please use the equivalent in example_msgs.
*/
public class UInt8 implements ROS2Message<UInt8>
{
   public static final String name = "std_msgs::msg::dds_::UInt8_";

   private byte data_;

   public UInt8()
   {
   }

   public byte getdata()
   {
      return data_;
   }

   public void setdata(byte data_)
   {
      this.data_ = data_;
   }


   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // data_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(data_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      data_ = buffer.readByte();

   }

   @Override
   public String getName()
   {
      return name;
   }

   @Override
   public void set(UInt8 from)
   {
      data_ = from.data_;

   }
}