/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(nav_msgs/Goals)
##################################################################################
##################################################################################

 */
package nav_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
*/
public class Goals implements ROS2Message<Goals>
{
   public static final java.lang.String name = "nav_msgs::msg::dds_::Goals_";

   /**
      # This header will store the time at which the poses were computed (not to be confused with the stamps of the poses themselves)
      # In the case that individual poses do not have their frame_id set or their timetamp set they will use the default value here.
   */
   private final nav_msgs.msg.dds.std_msgs/Header header_;
   /**
      # An array of goals to for navigation to achieve.
      # The goals should be executed in the order of the array.
      # The header and stamp are intended to be used for computing the position of the goals.
      # They may vary to support cases of goals that are moving with respect to the robot.
   */
   private final IDLObjectSequence<nav_msgs.msg.dds.geometry_msgs/PoseStamped> goals_;

   public Goals()
   {
      header_ = new nav_msgs.msg.dds.std_msgs/Header();
      goals_ = new IDLObjectSequence<nav_msgs.msg.dds.geometry_msgs/PoseStamped>(nav_msgs.msg.dds.geometry_msgs/PoseStamped.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += goals_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      goals_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      goals_.deserialize(buffer);

   }

   @Override
   public void set(Goals from)
   {
      header_.set(from.header_);
      goals_.set(from.goals_);

   }

   public nav_msgs.msg.dds.std_msgs/Header getHeader()
   {
      return header_;
   }

   public IDLObjectSequence<nav_msgs.msg.dds.geometry_msgs/PoseStamped> getGoals()
   {
      return goals_;
   }


}