/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(nav_msgs/Odometry)
##################################################################################
##################################################################################

 */
package nav_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   # This represents an estimate of a position and velocity in free space.
   # The pose in this message should be specified in the coordinate frame given by header.frame_id
   # The twist in this message should be specified in the coordinate frame given by the child_frame_id
*/
public class Odometry implements ROS2Message<Odometry>
{
   public static final java.lang.String name = "nav_msgs::msg::dds_::Odometry_";

   /**
      # Includes the frame id of the pose parent.
   */
   private final nav_msgs.msg.dds.std_msgs/Header header_;
   /**
      # Frame id the pose points to. The twist is in this coordinate frame.
   */
   private final StringBuilder child_frame_id_;
   /**
      # Estimated pose that is typically relative to a fixed world frame.
   */
   private final nav_msgs.msg.dds.geometry_msgs/PoseWithCovariance pose_;
   /**
      # Estimated linear and angular velocity relative to child_frame_id.
   */
   private final nav_msgs.msg.dds.geometry_msgs/TwistWithCovariance twist_;

   public Odometry()
   {
      header_ = new nav_msgs.msg.dds.std_msgs/Header();
      child_frame_id_ = new StringBuilder();
      pose_ = new nav_msgs.msg.dds.geometry_msgs/PoseWithCovariance();
      twist_ = new nav_msgs.msg.dds.geometry_msgs/TwistWithCovariance();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * child_frame_id_.length()) + 1; // child_frame_id_
      currentAlignment += pose_.calculateSizeBytes(currentAlignment);
      currentAlignment += twist_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      buffer.writeString(child_frame_id_);
      pose_.serialize(buffer);
      twist_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      buffer.readString(child_frame_id_);
      pose_.deserialize(buffer);
      twist_.deserialize(buffer);

   }

   @Override
   public void set(Odometry from)
   {
      header_.set(from.header_);
      child_frame_id_.delete(0, child_frame_id_.length());
      child_frame_id_.insert(0, from.child_frame_id_);
      pose_.set(from.pose_);
      twist_.set(from.twist_);

   }

   public nav_msgs.msg.dds.std_msgs/Header getHeader()
   {
      return header_;
   }

   public StringBuilder getChildFrameId()
   {
      return child_frame_id_;
   }

   public nav_msgs.msg.dds.geometry_msgs/PoseWithCovariance getPose()
   {
      return pose_;
   }

   public nav_msgs.msg.dds.geometry_msgs/TwistWithCovariance getTwist()
   {
      return twist_;
   }


}