/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package lifecycle_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (lifecycle_msgs/ChangeState_Response):
<pre>{@code
# Indicates whether the service was able to initiate the state transition
bool success}</pre>
*/
public class ChangeState_Response implements ROS2Message<ChangeState_Response>
{
   public static final java.lang.String name = "lifecycle_msgs::srv::dds_::ChangeStateResponse_";

   /**
      Indicates whether the service was able to initiate the state transition
   */
   private boolean success_;

   public ChangeState_Response()
   {
      success_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // success_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(success_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      success_ = buffer.readBoolean();

   }

   @Override
   public void set(ChangeState_Response from)
   {
      success_ = from.success_;

   }

   public boolean getSuccess()
   {
      return success_;
   }

   public void setSuccess(boolean success_)
   {
      this.success_ = success_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ChangeState_Response {");
      builder.append("success_=");
      builder.append(success_);

      builder.append("}");
      return builder.toString();
   }
}
