/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package lifecycle_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (lifecycle_msgs/GetAvailableStates_Request):
<pre>{@code
}</pre>
*/
public class GetAvailableStates_Request implements ROS2Message<GetAvailableStates_Request>
{
   public static final java.lang.String name = "lifecycle_msgs::srv::dds_::GetAvailableStatesRequest_";

   public GetAvailableStates_Request()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public void set(GetAvailableStates_Request from)
   {
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("GetAvailableStates_Request {");
      builder.append("}");
      return builder.toString();
   }
}
