/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 *
 * Original .msg file content (rcl_interfaces/ParameterEventDescriptors.msg):

# This message contains descriptors of a parameter event.
# It was an atomic update.
# A specific parameter name can only be in one of the three sets.

ParameterDescriptor[] new_parameters
ParameterDescriptor[] changed_parameters
ParameterDescriptor[] deleted_parameters


 */
package rcl_interfaces.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   This message contains descriptors of a parameter event.
   It was an atomic update.
   A specific parameter name can only be in one of the three sets.
*/
public class ParameterEventDescriptors implements ROS2Message<ParameterEventDescriptors>
{
   public static final java.lang.String name = "rcl_interfaces::msg::dds_::ParameterEventDescriptors_";

   private final IDLObjectSequence<rcl_interfaces.msg.dds.ParameterDescriptor> new_parameters_;
   private final IDLObjectSequence<rcl_interfaces.msg.dds.ParameterDescriptor> changed_parameters_;
   private final IDLObjectSequence<rcl_interfaces.msg.dds.ParameterDescriptor> deleted_parameters_;

   public ParameterEventDescriptors()
   {
      new_parameters_ = new IDLObjectSequence<rcl_interfaces.msg.dds.ParameterDescriptor>(rcl_interfaces.msg.dds.ParameterDescriptor.class);
      changed_parameters_ = new IDLObjectSequence<rcl_interfaces.msg.dds.ParameterDescriptor>(rcl_interfaces.msg.dds.ParameterDescriptor.class);
      deleted_parameters_ = new IDLObjectSequence<rcl_interfaces.msg.dds.ParameterDescriptor>(rcl_interfaces.msg.dds.ParameterDescriptor.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += new_parameters_.calculateSizeBytes(currentAlignment);
      currentAlignment += changed_parameters_.calculateSizeBytes(currentAlignment);
      currentAlignment += deleted_parameters_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      new_parameters_.serialize(buffer);
      changed_parameters_.serialize(buffer);
      deleted_parameters_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      new_parameters_.deserialize(buffer);
      changed_parameters_.deserialize(buffer);
      deleted_parameters_.deserialize(buffer);

   }

   @Override
   public void set(ParameterEventDescriptors from)
   {
      new_parameters_.set(from.new_parameters_);
      changed_parameters_.set(from.changed_parameters_);
      deleted_parameters_.set(from.deleted_parameters_);

   }

   public IDLObjectSequence<rcl_interfaces.msg.dds.ParameterDescriptor> getnew_parameters()
   {
      return new_parameters_;
   }

   public IDLObjectSequence<rcl_interfaces.msg.dds.ParameterDescriptor> getchanged_parameters()
   {
      return changed_parameters_;
   }

   public IDLObjectSequence<rcl_interfaces.msg.dds.ParameterDescriptor> getdeleted_parameters()
   {
      return deleted_parameters_;
   }


}