/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package geometry_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (geometry_msgs/AccelStamped):
<pre>{@code
# An accel with reference coordinate frame and timestamp
std_msgs/Header header
Accel accel
}</pre>
*/
public class AccelStamped implements ROS2Message<AccelStamped>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::AccelStamped_";

   /**
      An accel with reference coordinate frame and timestamp
   */
   private final std_msgs.Header header_;
   private final geometry_msgs.Accel accel_;

   public AccelStamped()
   {
      header_ = new std_msgs.Header();
      accel_ = new geometry_msgs.Accel();

   }

   public AccelStamped(AccelStamped from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += accel_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      accel_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      accel_.deserialize(buffer);

   }

   @Override
   public void set(AccelStamped from)
   {
      header_.set(from.header_);
      accel_.set(from.accel_);

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public geometry_msgs.Accel getAccel()
   {
      return accel_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("AccelStamped {");
      builder.append("header_=");
      builder.append(header_);
      builder.append("accel_=");
      builder.append(accel_);

      builder.append("}");
      return builder.toString();
   }
}