/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package geometry_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (geometry_msgs/Accel):
<pre>{@code
# This expresses acceleration in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular
}</pre>
*/
public class Accel implements ROS2Message<Accel>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::Accel_";

   /**
      This expresses acceleration in free space broken into its linear and angular parts.
   */
   private final geometry_msgs.Vector3 linear_;
   private final geometry_msgs.Vector3 angular_;

   public Accel()
   {
      linear_ = new geometry_msgs.Vector3();
      angular_ = new geometry_msgs.Vector3();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += linear_.calculateSizeBytes(currentAlignment);
      currentAlignment += angular_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      linear_.serialize(buffer);
      angular_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      linear_.deserialize(buffer);
      angular_.deserialize(buffer);

   }

   @Override
   public void set(Accel from)
   {
      linear_.set(from.linear_);
      angular_.set(from.angular_);

   }

   public geometry_msgs.Vector3 getLinear()
   {
      return linear_;
   }

   public geometry_msgs.Vector3 getAngular()
   {
      return angular_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Accel {");
      builder.append("linear_=");
      builder.append(linear_);
      builder.append("angular_=");
      builder.append(angular_);

      builder.append("}");
      return builder.toString();
   }
}