/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package geometry_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This represents a Point with reference coordinate frame and timestamp
<p>Source (geometry_msgs/PointStamped):
<pre>{@code
# This represents a Point with reference coordinate frame and timestamp

std_msgs/Header header
Point point
}</pre>
*/
public class PointStamped implements ROS2Message<PointStamped>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::PointStamped_";

   private final std_msgs.Header header_;
   private final geometry_msgs.Point point_;

   public PointStamped()
   {
      header_ = new std_msgs.Header();
      point_ = new geometry_msgs.Point();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += point_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      point_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      point_.deserialize(buffer);

   }

   @Override
   public void set(PointStamped from)
   {
      header_.set(from.header_);
      point_.set(from.point_);

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public geometry_msgs.Point getPoint()
   {
      return point_;
   }


}