/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package geometry_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This represents a Polygon with reference coordinate frame and timestamp
<p>Source (geometry_msgs/PolygonStamped):
<pre>{@code
# This represents a Polygon with reference coordinate frame and timestamp

std_msgs/Header header
Polygon polygon
}</pre>
*/
public class PolygonStamped implements ROS2Message<PolygonStamped>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::PolygonStamped_";

   private final std_msgs.Header header_;
   private final geometry_msgs.Polygon polygon_;

   public PolygonStamped()
   {
      header_ = new std_msgs.Header();
      polygon_ = new geometry_msgs.Polygon();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += polygon_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      polygon_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      polygon_.deserialize(buffer);

   }

   @Override
   public void set(PolygonStamped from)
   {
      header_.set(from.header_);
      polygon_.set(from.polygon_);

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public geometry_msgs.Polygon getPolygon()
   {
      return polygon_;
   }


}