/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package geometry_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This represents a Polygon with reference coordinate frame and timestamp
It includes a unique identification field for disambiguating multiple instances
<p>Source (geometry_msgs/PolygonInstanceStamped):
<pre>{@code
# This represents a Polygon with reference coordinate frame and timestamp
# It includes a unique identification field for disambiguating multiple instances

std_msgs/Header header
geometry_msgs/PolygonInstance polygon
}</pre>
*/
public class PolygonInstanceStamped implements ROS2Message<PolygonInstanceStamped>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::PolygonInstanceStamped_";

   private final std_msgs.Header header_;
   private final geometry_msgs.PolygonInstance polygon_;

   public PolygonInstanceStamped()
   {
      header_ = new std_msgs.Header();
      polygon_ = new geometry_msgs.PolygonInstance();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += polygon_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      polygon_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      polygon_.deserialize(buffer);

   }

   @Override
   public void set(PolygonInstanceStamped from)
   {
      header_.set(from.header_);
      polygon_.set(from.polygon_);

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public geometry_msgs.PolygonInstance getPolygon()
   {
      return polygon_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("PolygonInstanceStamped {");
      builder.append("header_=");
      builder.append(header_);
      builder.append("polygon_=");
      builder.append(polygon_);

      builder.append("}");
      return builder.toString();
   }
}