/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package geometry_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This expresses velocity in free space with uncertainty.
<p>Source (geometry_msgs/TwistWithCovariance):
<pre>{@code
# This expresses velocity in free space with uncertainty.

Twist twist

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance
}</pre>
*/
public class TwistWithCovariance implements ROS2Message<TwistWithCovariance>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::TwistWithCovariance_";

   private final geometry_msgs.Twist twist_;
   /**
      Row-major representation of the 6x6 covariance matrix
      The orientation parameters use a fixed-axis representation.
      In order, the parameters are:
      (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
   */
   private final double[] covariance_;

   public TwistWithCovariance()
   {
      twist_ = new geometry_msgs.Twist();
      covariance_ = new double[36];

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += twist_.calculateSizeBytes(currentAlignment);
      currentAlignment += (36 * 8) + CDRBuffer.alignment(currentAlignment, (36 * 8)); // covariance_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      twist_.serialize(buffer);
      for (int i = 0; i < covariance_.length; ++i)
      {
         buffer.writeDouble(covariance_[i]);
      }

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      twist_.deserialize(buffer);
      for (int i = 0; i < covariance_.length; ++i)
      {
         covariance_[i] = buffer.readDouble();
      }

   }

   @Override
   public void set(TwistWithCovariance from)
   {
      twist_.set(from.twist_);
      for (int i = 0; i < covariance_.length; ++i)
      {
         covariance_[i] = from.covariance_[i];
      }

   }

   public geometry_msgs.Twist getTwist()
   {
      return twist_;
   }

   public double[] getCovariance()
   {
      return covariance_;
   }


}