/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package geometry_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This represents force in free space, separated into its linear and angular parts.
<p>Source (geometry_msgs/Wrench):
<pre>{@code
# This represents force in free space, separated into its linear and angular parts.

Vector3  force
Vector3  torque
}</pre>
*/
public class Wrench implements ROS2Message<Wrench>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::Wrench_";

   private final geometry_msgs.Vector3 force_;
   private final geometry_msgs.Vector3 torque_;

   public Wrench()
   {
      force_ = new geometry_msgs.Vector3();
      torque_ = new geometry_msgs.Vector3();

   }

   public Wrench(Wrench from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += force_.calculateSizeBytes(currentAlignment);
      currentAlignment += torque_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      force_.serialize(buffer);
      torque_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      force_.deserialize(buffer);
      torque_.deserialize(buffer);

   }

   @Override
   public void set(Wrench from)
   {
      force_.set(from.force_);
      torque_.set(from.torque_);

   }

   public geometry_msgs.Vector3 getForce()
   {
      return force_;
   }

   public geometry_msgs.Vector3 getTorque()
   {
      return torque_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Wrench {");
      builder.append("force_=");
      builder.append(force_);
      builder.append("torque_=");
      builder.append(torque_);

      builder.append("}");
      return builder.toString();
   }
}