// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.fastdds;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.fastdds.global.fastdds.*;


/** \brief A structure storing the subscription status */
@Namespace("eprosima::fastdds::dds") @Properties(inherit = us.ihmc.fastdds.fastddsConfig.class)
public class SubscriptionMatchedStatus extends MatchedStatus {
    static { Loader.load(); }
    /** Default native constructor. */
    public SubscriptionMatchedStatus() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SubscriptionMatchedStatus(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SubscriptionMatchedStatus(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SubscriptionMatchedStatus position(long position) {
        return (SubscriptionMatchedStatus)super.position(position);
    }
    @Override public SubscriptionMatchedStatus getPointer(long i) {
        return new SubscriptionMatchedStatus((Pointer)this).offsetAddress(i);
    }

    /** \brief Handle to the last writer that matched the reader causing the status change */
}
