/*
 * This class was automatically generated by jros2
 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class AccelWithCovarianceStamped implements ROS2Message<AccelWithCovarianceStamped>
{
   public static final String name = "geometry_msgs::msg::dds_::AccelWithCovarianceStamped_";

   private geometry_msgs.msg.dds.AccelWithCovariance accel_;

   public AccelWithCovarianceStamped()
   {
   }

   public geometry_msgs.msg.dds.AccelWithCovariance getaccel()
   {
      return accel_;
   }


   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public String getName()
   {
      return name;
   }

   @Override
   public void set(AccelWithCovarianceStamped from)
   {
   }
}