/*
 * This class was automatically generated by jros2
 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   This represents a Point with reference coordinate frame and timestamp
*/
public class PointStamped implements ROS2Message<PointStamped>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::PointStamped_";

   private geometry_msgs.msg.dds.Point point_;

   public PointStamped()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(PointStamped from)
   {
   }

   public geometry_msgs.msg.dds.Point getpoint()
   {
      return point_;
   }


}