/*
 * This class was automatically generated by jros2
 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class Point implements ROS2Message<Point>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::Point_";

   /**
       This contains the position of a point in free space
   */
   private double x_;
   private double y_;
   private double z_;

   public Point()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // x_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // y_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // z_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(x_);
      buffer.writeDouble(y_);
      buffer.writeDouble(z_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      x_ = buffer.readDouble();
      y_ = buffer.readDouble();
      z_ = buffer.readDouble();

   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(Point from)
   {
      x_ = from.x_;
      y_ = from.y_;
      z_ = from.z_;

   }

   public double getx()
   {
      return x_;
   }

   public void setx(double x_)
   {
      this.x_ = x_;
   }

   public double gety()
   {
      return y_;
   }

   public void sety(double y_)
   {
      this.y_ = y_;
   }

   public double getz()
   {
      return z_;
   }

   public void setz(double z_)
   {
      this.z_ = z_;
   }


}