/*
 * This class was automatically generated by jros2
 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
    A Pose with reference coordinate frame and timestamp
*/
public class PoseStamped implements ROS2Message<PoseStamped>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::PoseStamped_";

   private geometry_msgs.msg.dds.Pose pose_;

   public PoseStamped()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(PoseStamped from)
   {
   }

   public geometry_msgs.msg.dds.Pose getpose()
   {
      return pose_;
   }


}