/*
 * This class was automatically generated by jros2
 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
    This expresses an estimated pose with a reference coordinate frame and timestamp
*/
public class PoseWithCovarianceStamped implements ROS2Message<PoseWithCovarianceStamped>
{
   public static final String name = "geometry_msgs::msg::dds_::PoseWithCovarianceStamped_";

   private geometry_msgs.msg.dds.PoseWithCovariance pose_;

   public PoseWithCovarianceStamped()
   {
   }

   public geometry_msgs.msg.dds.PoseWithCovariance getpose()
   {
      return pose_;
   }


   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public String getName()
   {
      return name;
   }

   @Override
   public void set(PoseWithCovarianceStamped from)
   {
   }
}