/*
 * This class was automatically generated by jros2
 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
    This expresses velocity in free space broken into its linear and angular parts.
*/
public class Twist implements ROS2Message<Twist>
{
   public static final String name = "geometry_msgs::msg::dds_::Twist_";

   public Twist()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public String getName()
   {
      return name;
   }

   @Override
   public void set(Twist from)
   {
   }

}