/*
 * This class was automatically generated by jros2
 */
package geometry_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   This represents an estimated twist with reference coordinate frame and timestamp.
*/
public class TwistWithCovarianceStamped implements ROS2Message<TwistWithCovarianceStamped>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::TwistWithCovarianceStamped_";

   private geometry_msgs.msg.dds.std_msgs/Header header_;
   private geometry_msgs.msg.dds.TwistWithCovariance twist_;

   public TwistWithCovarianceStamped()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public java.lang.String getName()
   {
      return name;
   }

   @Override
   public void set(TwistWithCovarianceStamped from)
   {
   }

   public geometry_msgs.msg.dds.std_msgs/Header getheader()
   {
      return header_;
   }

   public geometry_msgs.msg.dds.TwistWithCovariance gettwist()
   {
      return twist_;
   }


}