/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package rcl_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (rcl_interfaces/DescribeParameters_Request):
<pre>{@code
# A list of parameters of which to get the descriptor.
string[] names}</pre>
*/
public class DescribeParameters_Request implements ROS2Message<DescribeParameters_Request>
{
   public static final java.lang.String name = "rcl_interfaces::srv::dds_::DescribeParametersRequest_";

   /**
      A list of parameters of which to get the descriptor.
   */
   private final IDLStringSequence names_;

   public DescribeParameters_Request()
   {
      names_ = new IDLStringSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += names_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      names_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      names_.deserialize(buffer);

   }

   @Override
   public void set(DescribeParameters_Request from)
   {
      names_.set(from.names_);

   }

   public IDLStringSequence getNames()
   {
      return names_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("DescribeParameters_Request {");
      builder.append("names_=");
      builder.append(names_);

      builder.append("}");
      return builder.toString();
   }
}
