/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package rcl_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (rcl_interfaces/GetParameterTypes_Response):
<pre>{@code
# List of types which is the same length and order as the provided names.
#
# The type enum is defined in ParameterType.msg. ParameterType.PARAMETER_NOT_SET
# indicates that the parameter is not currently set.
uint8[] types}</pre>
*/
public class GetParameterTypes_Response implements ROS2Message<GetParameterTypes_Response>
{
   public static final java.lang.String name = "rcl_interfaces::msg::dds_::GetParameterTypesResponse_";

   /**
      List of types which is the same length and order as the provided names.

      The type enum is defined in ParameterType.msg. ParameterType.PARAMETER_NOT_SET
      indicates that the parameter is not currently set.
   */
   private final IDLShortSequence types_;

   public GetParameterTypes_Response()
   {
      types_ = new IDLShortSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += types_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      types_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      types_.deserialize(buffer);

   }

   @Override
   public void set(GetParameterTypes_Response from)
   {
      types_.set(from.types_);

   }

   public IDLShortSequence getTypes()
   {
      return types_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("GetParameterTypes_Response {");
      builder.append("types_=");
      builder.append(types_);

      builder.append("}");
      return builder.toString();
   }
}
