/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package rcl_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (rcl_interfaces/GetParameters_Response):
<pre>{@code
# List of values which is the same length and order as the provided names. If a
# parameter was not yet set, the value will have PARAMETER_NOT_SET as the
# type.
ParameterValue[] values}</pre>
*/
public class GetParameters_Response implements ROS2Message<GetParameters_Response>
{
   public static final java.lang.String name = "rcl_interfaces::srv::dds_::GetParametersResponse_";

   /**
      List of values which is the same length and order as the provided names. If a
      parameter was not yet set, the value will have PARAMETER_NOT_SET as the
      type.
   */
   private final IDLObjectSequence<rcl_interfaces.ParameterValue> values_;

   public GetParameters_Response()
   {
      values_ = new IDLObjectSequence<rcl_interfaces.ParameterValue>(rcl_interfaces.ParameterValue.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += values_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      values_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      values_.deserialize(buffer);

   }

   @Override
   public void set(GetParameters_Response from)
   {
      values_.set(from.values_);

   }

   public IDLObjectSequence<rcl_interfaces.ParameterValue> getValues()
   {
      return values_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("GetParameters_Response {");
      builder.append("values_=");
      builder.append(values_);

      builder.append("}");
      return builder.toString();
   }
}
