/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package rcl_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (rcl_interfaces/ListParametersResult):
<pre>{@code
# The resulting parameters under the given prefixes.
string[] names

# The resulting prefixes under the given prefixes.
# TODO(wjwwood): link to prefix definition and rules.
string[] prefixes
}</pre>
*/
public class ListParametersResult implements ROS2Message<ListParametersResult>
{
   public static final java.lang.String name = "rcl_interfaces::msg::dds_::ListParametersResult_";

   /**
      The resulting parameters under the given prefixes.
   */
   private final IDLStringSequence names_;
   /**
      The resulting prefixes under the given prefixes.
      TODO(wjwwood): link to prefix definition and rules.
   */
   private final IDLStringSequence prefixes_;

   public ListParametersResult()
   {
      names_ = new IDLStringSequence();
      prefixes_ = new IDLStringSequence();

   }

   public ListParametersResult(ListParametersResult from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += names_.calculateSizeBytes(currentAlignment);
      currentAlignment += prefixes_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      names_.serialize(buffer);
      prefixes_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      names_.deserialize(buffer);
      prefixes_.deserialize(buffer);

   }

   @Override
   public void set(ListParametersResult from)
   {
      names_.set(from.names_);
      prefixes_.set(from.prefixes_);

   }

   public IDLStringSequence getNames()
   {
      return names_;
   }

   public IDLStringSequence getPrefixes()
   {
      return prefixes_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ListParametersResult {");
      builder.append("names_=");
      builder.append(names_);
      builder.append("prefixes_=");
      builder.append(prefixes_);

      builder.append("}");
      return builder.toString();
   }
}