/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package rcl_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (rcl_interfaces/ListParameters_Response):
<pre>{@code
# The list of parameter names and their prefixes.
ListParametersResult result}</pre>
*/
public class ListParameters_Response implements ROS2Message<ListParameters_Response>
{
   public static final java.lang.String name = "rcl_interfaces::msg::dds_::ListParametersResponse_";

   /**
      The list of parameter names and their prefixes.
   */
   private final rcl_interfaces.ListParametersResult result_;

   public ListParameters_Response()
   {
      result_ = new rcl_interfaces.ListParametersResult();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += result_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      result_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      result_.deserialize(buffer);

   }

   @Override
   public void set(ListParameters_Response from)
   {
      result_.set(from.result_);

   }

   public rcl_interfaces.ListParametersResult getResult()
   {
      return result_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ListParameters_Response {");
      builder.append("result_=");
      builder.append(result_);

      builder.append("}");
      return builder.toString();
   }
}
