/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package rcl_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message contains descriptors of a parameter event.
It was an atomic update.
A specific parameter name can only be in one of the three sets.
<p>Source (rcl_interfaces/ParameterEventDescriptors):
<pre>{@code
# This message contains descriptors of a parameter event.
# It was an atomic update.
# A specific parameter name can only be in one of the three sets.

ParameterDescriptor[] new_parameters
ParameterDescriptor[] changed_parameters
ParameterDescriptor[] deleted_parameters
}</pre>
*/
public class ParameterEventDescriptors implements ROS2Message<ParameterEventDescriptors>
{
   public static final java.lang.String name = "rcl_interfaces::msg::dds_::ParameterEventDescriptors_";

   private final IDLObjectSequence<rcl_interfaces.ParameterDescriptor> new_parameters_;
   private final IDLObjectSequence<rcl_interfaces.ParameterDescriptor> changed_parameters_;
   private final IDLObjectSequence<rcl_interfaces.ParameterDescriptor> deleted_parameters_;

   public ParameterEventDescriptors()
   {
      new_parameters_ = new IDLObjectSequence<rcl_interfaces.ParameterDescriptor>(rcl_interfaces.ParameterDescriptor.class);
      changed_parameters_ = new IDLObjectSequence<rcl_interfaces.ParameterDescriptor>(rcl_interfaces.ParameterDescriptor.class);
      deleted_parameters_ = new IDLObjectSequence<rcl_interfaces.ParameterDescriptor>(rcl_interfaces.ParameterDescriptor.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += new_parameters_.calculateSizeBytes(currentAlignment);
      currentAlignment += changed_parameters_.calculateSizeBytes(currentAlignment);
      currentAlignment += deleted_parameters_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      new_parameters_.serialize(buffer);
      changed_parameters_.serialize(buffer);
      deleted_parameters_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      new_parameters_.deserialize(buffer);
      changed_parameters_.deserialize(buffer);
      deleted_parameters_.deserialize(buffer);

   }

   @Override
   public void set(ParameterEventDescriptors from)
   {
      new_parameters_.set(from.new_parameters_);
      changed_parameters_.set(from.changed_parameters_);
      deleted_parameters_.set(from.deleted_parameters_);

   }

   public IDLObjectSequence<rcl_interfaces.ParameterDescriptor> getNewParameters()
   {
      return new_parameters_;
   }

   public IDLObjectSequence<rcl_interfaces.ParameterDescriptor> getChangedParameters()
   {
      return changed_parameters_;
   }

   public IDLObjectSequence<rcl_interfaces.ParameterDescriptor> getDeletedParameters()
   {
      return deleted_parameters_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ParameterEventDescriptors {");
      builder.append("new_parameters_=");
      builder.append(new_parameters_);
      builder.append("changed_parameters_=");
      builder.append(changed_parameters_);
      builder.append("deleted_parameters_=");
      builder.append(deleted_parameters_);

      builder.append("}");
      return builder.toString();
   }
}