/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package rcl_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (rcl_interfaces/SetParameters_Response):
<pre>{@code
# Indicates whether setting each parameter succeeded or not and why.
SetParametersResult[] results}</pre>
*/
public class SetParameters_Response implements ROS2Message<SetParameters_Response>
{
   public static final java.lang.String name = "rcl_interfaces::srv::dds_::SetParametersResponse_";

   /**
      Indicates whether setting each parameter succeeded or not and why.
   */
   private final IDLObjectSequence<rcl_interfaces.SetParametersResult> results_;

   public SetParameters_Response()
   {
      results_ = new IDLObjectSequence<rcl_interfaces.SetParametersResult>(rcl_interfaces.SetParametersResult.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += results_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      results_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      results_.deserialize(buffer);

   }

   @Override
   public void set(SetParameters_Response from)
   {
      results_.set(from.results_);

   }

   public IDLObjectSequence<rcl_interfaces.SetParametersResult> getResults()
   {
      return results_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("SetParameters_Response {");
      builder.append("results_=");
      builder.append(results_);

      builder.append("}");
      return builder.toString();
   }
}
