/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package rcl_interfaces;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (rcl_interfaces/SetParametersAtomically_Request):
<pre>{@code
# A list of parameters to set atomically.
#
# This call will either set all values, or none of the values.
Parameter[] parameters}</pre>
*/
public class SetParametersAtomically_Request implements ROS2Message<SetParametersAtomically_Request>
{
   public static final java.lang.String name = "rcl_interfaces::msg::dds_::SetParametersAtomicallyRequest_";

   /**
      A list of parameters to set atomically.

      This call will either set all values, or none of the values.
   */
   private final IDLObjectSequence<rcl_interfaces.Parameter> parameters_;

   public SetParametersAtomically_Request()
   {
      parameters_ = new IDLObjectSequence<rcl_interfaces.Parameter>(rcl_interfaces.Parameter.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += parameters_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      parameters_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      parameters_.deserialize(buffer);

   }

   @Override
   public void set(SetParametersAtomically_Request from)
   {
      parameters_.set(from.parameters_);

   }

   public IDLObjectSequence<rcl_interfaces.Parameter> getParameters()
   {
      return parameters_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("SetParametersAtomically_Request {");
      builder.append("parameters_=");
      builder.append(parameters_);

      builder.append("}");
      return builder.toString();
   }
}
