# https://design.ros2.org/articles/interface_definition.html

string str1 ""
string str2 ""
string str3 ""
string str4 ""
string str5 "''"
string str6 \"""
string str7 '""'
string str8 Hello World
string str9 "Hello World"
string stra 'Hello World'
string strb Hello "World"
string strc Hello 'World'
string strd "Hello" World
string stre 'Hello' World
string strf "Hello 'World'"
string strg 'Hello "World"'
string strh "Hello" 'World'
string stri 'Hello' "World"
string strj   Hello World  
string strk "  Hello World  "
string strl '  Goodbye World  '
