// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.fastddsjava.pointers;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.fastddsjava.pointers.fastddsjava.*;


@NoOffset @Properties(inherit = us.ihmc.fastddsjava.pointers.fastddsjavaInfoMapper.class)
public class fastddsjava_TopicDataWrapperType extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public fastddsjava_TopicDataWrapperType(Pointer p) { super(p); }

    public fastddsjava_TopicDataWrapperType(@StdString BytePointer name, @Cast("uint16_t") short encapsulation) { super((Pointer)null); allocate(name, encapsulation); }
    private native void allocate(@StdString BytePointer name, @Cast("uint16_t") short encapsulation);
    public fastddsjava_TopicDataWrapperType(@StdString String name, @Cast("uint16_t") short encapsulation) { super((Pointer)null); allocate(name, encapsulation); }
    private native void allocate(@StdString String name, @Cast("uint16_t") short encapsulation);

    public native Pointer create_data();

    public native void delete_data(Pointer data);

    public native @StdString BytePointer get_name();

}
