name: Build natives

on:
  workflow_dispatch:

jobs:
  gradle-test:
    runs-on: self-hosted
    container:
      image: ubuntu:20.04
      env:
        TZ: "America/Chicago"
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y install build-essential cmake curl unzip openjdk-17-jdk jaxb

      - name: Compile
        run: |
          bash cppbuild.bash