name: Build natives

on:
  workflow_dispatch:

jobs:
  build-natives-linux:
    runs-on: self-hosted
    container:
      image: ubuntu:20.04
      env:
        TZ: "America/Chicago"
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y install build-essential git curl wget unzip openjdk-17-jdk jaxb
          # Install newer version of cmake
          wget https://github.com/Kitware/CMake/releases/download/v4.0.2/cmake-4.0.2-linux-x86_64.tar.gz
          tar -xzvf cmake-4.0.2-linux-x86_64.tar.gz
          mv cmake-4.0.2-linux-x86_64 /opt/cmake-4.0.2
          rm -rf cmake-4.0.2-linux-x86_64.tar.gz
      - name: Compile
        run: |
          PATH=/opt/cmake-4.0.2/bin:$PATH bash cppbuild.bash
          ls -al
      - name: Commit generated java and native libraries
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.java *.so *.so.*' # Only commit generated java from Linux
          author_name: ihmc-rosie
          author_email: rosie@ihmc.us
          message: 'Rebuild natives for Linux (x86_64)'
          push: true