name: Build natives

on:
  workflow_dispatch:

jobs:
  gradle-test:
    runs-on: self-hosted
    container:
      image: ubuntu:20.04
      env:
        TZ: "America/Chicago"
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y install build-essential git curl unzip openjdk-17-jdk jaxb
          # Install newer version of cmake
          bash <(wget -qO- https://apt.kitware.com/kitware-archive.sh)
          apt-get -y install cmake

      - name: Compile
        run: |
          bash cppbuild.bash