package us.ihmc.jros2.generator;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class GeneratedMessageFileCleanupTest
{
   @TempDir
   Path tempDir;

   @Test
   public void testIsJros2GeneratedFile() throws Exception
   {
      Path generatedFile = tempDir.resolve("Generated.java");
      Files.writeString(generatedFile, """
         /*
          * This class was automatically generated by jros2.
          * Do not modify this file directly.
          */
         public class Generated {}
         """);

      Path handWrittenFile = tempDir.resolve("HandWritten.java");
      Files.writeString(handWrittenFile, "public class HandWritten {}");

      assertTrue(GeneratedMessageFileCleanup.isJros2GeneratedFile(generatedFile));
      assertFalse(GeneratedMessageFileCleanup.isJros2GeneratedFile(handWrittenFile));
   }

   @Test
   public void testRemoveOrphanedGeneratedFiles() throws Exception
   {
      Path packageDir = tempDir.resolve("test_msgs");
      Files.createDirectories(packageDir);

      Path keptFile = packageDir.resolve("Kept.java");
      Files.writeString(keptFile, jros2GeneratedClass("Kept"));

      Path orphanFile = packageDir.resolve("Orphan.java");
      Files.writeString(orphanFile, jros2GeneratedClass("Orphan"));

      Path handWrittenFile = packageDir.resolve("Manual.java");
      Files.writeString(handWrittenFile, "public class Manual {}");

      int removed = GeneratedMessageFileCleanup.removeOrphanedGeneratedFiles(tempDir, Set.of(keptFile.toAbsolutePath().normalize()));

      assertTrue(Files.exists(keptFile));
      assertFalse(Files.exists(orphanFile));
      assertTrue(Files.exists(handWrittenFile));
      assertTrue(removed >= 1);
   }

   @Test
   public void testCleanOutputDirectory() throws Exception
   {
      Path packageDir = tempDir.resolve("test_msgs");
      Files.createDirectories(packageDir);
      Path generatedFile = packageDir.resolve("Generated.java");
      Files.writeString(generatedFile, jros2GeneratedClass("Generated"));

      GeneratedMessageFileCleanup.cleanOutputDirectory(tempDir);

      assertFalse(Files.exists(generatedFile));
      assertTrue(Files.exists(tempDir));
   }

   private static String jros2GeneratedClass(String className)
   {
      return """
         /*
          * This class was automatically generated by jros2.
          * Do not modify this file directly.
          */
         public class %s {}
         """.formatted(className);
   }
}
